"use server";
import {redirect} from "next/navigation";
import {prisma} from "@/lib/prisma";
import {requireStaffPermission} from "@/lib/staff/authorization";
import {issueEmailVerification,issuePasswordReset} from "@/lib/auth/service";
import {deliverIdentityToken} from "@/lib/auth/delivery";
import {mergePilotRecords} from "@/lib/hr/pilot-merge";
import {HISPAFLY_HUB_ICAOS} from "@/lib/native-flight/hubs";
const v=(f:FormData,k:string)=>String(f.get(k)??"").trim();
export async function updatePilotAction(form:FormData){const id=v(form,"id"),staff=await requireStaffPermission("PILOT_EDIT",{entityType:"Pilot",entityId:id,attemptedAction:"edit Pilot profile"});const pilot=await prisma.pilot.findUnique({where:{id},include:{authUser:true}});if(!pilot)redirect("/staff/pilots?error=not_found");const email=v(form,"email").toLowerCase()||null,displayName=`${v(form,"firstName")} ${v(form,"lastName")}`.trim(),hubId=v(form,"hubId").toUpperCase();if(!HISPAFLY_HUB_ICAOS.includes(hubId as (typeof HISPAFLY_HUB_ICAOS)[number]))redirect(`/staff/pilots/${id}?error=invalid_hub`);try{await prisma.$transaction([prisma.pilot.update({where:{id},data:{firstName:v(form,"firstName")||null,lastName:v(form,"lastName")||null,displayName,callsign:v(form,"callsign").toUpperCase()||null,email,hubId,base:hubId,status:v(form,"status") as "active"|"inactive"|"on_leave"}}),...(pilot.authUser&&email?[prisma.authUser.update({where:{id:pilot.authUser.id},data:{email,displayName}})]:[]),prisma.aocAuditLog.create({data:{staffUserId:staff.id,action:pilot.hubId===hubId?"PILOT_PROFILE_UPDATED":"PILOT_HUB_CHANGED",entityType:"Pilot",entityId:id,message:`RRHH updated ${displayName}.`,metadata:{previousHub:pilot.hubId,newHub:hubId}}})]);}catch(error){redirect(`/staff/pilots/${id}?error=${encodeURIComponent(error instanceof Error?error.message:"update_failed")}`)}redirect(`/staff/pilots/${id}?success=updated`)}
export async function updatePilotPositionAction(form:FormData){const id=v(form,"id"),airportId=v(form,"airportId")||null,staff=await requireStaffPermission("PILOT_EDIT",{entityType:"Pilot",entityId:id,attemptedAction:"update Pilot crew position"});const airport=airportId?await prisma.airport.findFirst({where:{id:airportId,status:"ACTIVE",archivedAt:null},select:{id:true,icao:true}}):null;if(airportId&&!airport)redirect(`/staff/pilots/${id}?error=invalid_airport`);await prisma.$transaction([prisma.pilot.update({where:{id},data:{currentAirportId:airport?.id??null,positionUpdatedAt:new Date(),positionSource:"STAFF_OVERRIDE"}}),prisma.aocAuditLog.create({data:{staffUserId:staff.id,action:"PILOT_POSITION_UPDATED",entityType:"Pilot",entityId:id,message:airport?`Staff moved pilot crew position to ${airport.icao}.`:"Staff cleared the pilot crew position."}})]);redirect(`/staff/pilots/${id}?success=position_updated`)}
export async function resendVerificationByStaff(form:FormData){const id=v(form,"id"),email=v(form,"email");const staff=await requireStaffPermission("PILOT_IDENTITY_MANAGE",{entityType:"Pilot",entityId:id,attemptedAction:"resend verification email"});const issued=await issueEmailVerification(email);if(!issued)redirect(`/staff/pilots/${id}?error=verification_unavailable`);await deliverIdentityToken({type:"verify_email",email:issued.user.email,token:issued.token});await prisma.aocAuditLog.create({data:{staffUserId:staff.id,action:"PILOT_VERIFICATION_RESENT",entityType:"Pilot",entityId:id,message:"RRHH resent the verification email."}});redirect(`/staff/pilots/${id}?success=verification_sent`)}
export async function sendPasswordResetByStaff(form:FormData){const id=v(form,"id"),email=v(form,"email");const staff=await requireStaffPermission("PILOT_PASSWORD_RESET",{entityType:"Pilot",entityId:id,attemptedAction:"send password reset"});const token=await issuePasswordReset(email);if(!token)redirect(`/staff/pilots/${id}?error=reset_unavailable`);await deliverIdentityToken({type:"reset_password",email,token});await prisma.aocAuditLog.create({data:{staffUserId:staff.id,action:"PILOT_PASSWORD_RESET_SENT",entityType:"Pilot",entityId:id,message:"RRHH sent a password reset email."}});redirect(`/staff/pilots/${id}?success=reset_sent`)}
export async function mergePilotAction(form:FormData){const targetId=v(form,"targetId"),sourceId=v(form,"sourceId"),confirmation=v(form,"confirmation");const staff=await requireStaffPermission("PILOT_MERGE",{entityType:"Pilot",entityId:targetId,attemptedAction:"merge Pilot accounts"});if(confirmation!=="MERGE")redirect(`/staff/pilots/${targetId}?error=type_merge_to_confirm`);try{await mergePilotRecords(sourceId,targetId,staff.id)}catch(error){redirect(`/staff/pilots/${targetId}?error=${encodeURIComponent(error instanceof Error?error.message:"merge_failed")}`)}redirect(`/staff/pilots/${targetId}?success=merged`)}
