import Link from "next/link";
import {notFound} from "next/navigation";
import {prisma} from "@/lib/prisma";
import {requireStaffPermission} from "@/lib/staff/authorization";
import {resendVerificationByStaff,sendPasswordResetByStaff,updatePilotAction} from "./actions";
import {setPilotIdentityStatus,setPilotTemporaryPassword} from "../identity-actions";
export const dynamic="force-dynamic";
export default async function PilotDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{success?:string;error?:string}>}){
 const {id}=await params;await requireStaffPermission("PILOT_VIEW",{entityType:"Pilot",entityId:id,attemptedAction:"view Pilot RRHH record"});
 const [pilot,q,candidates,audit]=await Promise.all([
  prisma.pilot.findUnique({where:{id},include:{authUser:true,_count:{select:{pireps:true,payrollRecords:true,walletTransactions:true,flightDispatches:true,pilotBookings:true,efbPerformanceCalculations:true}}}}),
  searchParams,
  prisma.pilot.findMany({where:{id:{not:id}},select:{id:true,displayName:true,callsign:true,email:true,vamsysPilotId:true,authUserId:true},orderBy:{displayName:"asc"},take:500}),
  prisma.aocAuditLog.findMany({where:{OR:[{entityType:"Pilot",entityId:id},{metadata:{path:["pilotId"],equals:id}}]},orderBy:{createdAt:"desc"},take:12})
 ]);if(!pilot)notFound();const user=pilot.authUser;
 return <><div className="page-header"><div><div className="eyebrow">RRHH · {pilot.callsign??"PILOT"}</div><h1>{pilot.displayName}</h1><p>{pilot.email??"No email"} · {pilot.rankName??pilot.rank??"No rank"} · {pilot.base??"No base"}</p></div><Link className="button secondary" href="/staff/pilots">Back to pilots</Link></div>
 {q.success&&<div className="notice success">{q.success}</div>}{q.error&&<div className="notice error">{q.error}</div>}
 <div className="detail-grid"><section className="card"><h2>Profile</h2><form action={updatePilotAction} className="form-grid"><input type="hidden" name="id" value={id}/><label>First name<input name="firstName" defaultValue={pilot.firstName??""} required/></label><label>Last name<input name="lastName" defaultValue={pilot.lastName??""} required/></label><label>Email<input name="email" type="email" defaultValue={pilot.email??""}/></label><label>Callsign<input name="callsign" defaultValue={pilot.callsign??""}/></label><label>Base<input name="base" defaultValue={pilot.base??""}/></label><label>Rank<input name="rankName" defaultValue={pilot.rankName??pilot.rank??""}/></label><label>Status<select name="status" defaultValue={pilot.status}><option value="active">Active</option><option value="on_leave">On leave</option><option value="inactive">Inactive</option></select></label><button className="button">SAVE PROFILE</button></form></section>
 <section className="card"><h2>Operational history</h2><p>PIREPs: <strong>{pilot._count.pireps}</strong></p><p>Payroll records: <strong>{pilot._count.payrollRecords}</strong></p><p>Wallet transactions: <strong>{pilot._count.walletTransactions}</strong></p><p>Dispatches: <strong>{pilot._count.flightDispatches}</strong></p><p>Bookings: <strong>{pilot._count.pilotBookings}</strong></p><p>EFB calculations: <strong>{pilot._count.efbPerformanceCalculations}</strong></p><p>VAMSYS Pilot ID: {pilot.vamsysPilotId??"—"}</p></section>
 <section className="card"><h2>Local identity</h2>{user?<><p>{user.email}</p><p>Status: {user.status}</p><p>Verified: {user.emailVerifiedAt?.toLocaleString()??"No"}</p><div className="button-row"><form action={setPilotIdentityStatus}><input type="hidden" name="pilotId" value={id}/><input type="hidden" name="userId" value={user.id}/><input type="hidden" name="enabled" value={user.status==="DISABLED"?"true":"false"}/><button className="action-button">{user.status==="DISABLED"?"Enable account":"Disable account"}</button></form>{user.status==="PENDING_VERIFICATION"&&<form action={resendVerificationByStaff}><input type="hidden" name="id" value={id}/><input type="hidden" name="email" value={user.email}/><button className="action-button">Resend verification</button></form>}<form action={sendPasswordResetByStaff}><input type="hidden" name="id" value={id}/><input type="hidden" name="email" value={user.email}/><button className="action-button">Email reset link</button></form></div><form action={setPilotTemporaryPassword} className="inline-form"><input type="hidden" name="pilotId" value={id}/><input type="hidden" name="userId" value={user.id}/><input name="temporaryPassword" type="password" minLength={12} placeholder="Temporary password" required/><button className="action-button">Set temporary password</button></form></>:<p>No local login is attached to this Pilot.</p>}</section></div>
 <section className="card danger-zone"><h2>Merge duplicate or legacy record</h2><p>Select a source record to review both accounts, transferred history and risk warnings before the merge can be executed.</p><form action={`/staff/pilots/${id}/merge`} method="get" className="form-grid"><label>Source Pilot<select name="sourceId" required defaultValue=""><option value="" disabled>Select duplicate record</option>{candidates.map(c=><option key={c.id} value={c.id}>{c.displayName} · {c.callsign??"no callsign"} · {c.email??"no email"} · {c.vamsysPilotId?"VAMSYS":"local"}{c.authUserId?" · login":""}</option>)}</select></label><button className="button danger">REVIEW MERGE</button></form></section>
 <section className="card"><h2>Recent audit activity</h2>{audit.length?audit.map(row=><p key={row.id}><strong>{row.action}</strong> · {row.createdAt.toLocaleString()}<br/><span className="meta">{row.message}</span></p>):<p className="meta">No RRHH audit events yet.</p>}</section></>;
}
