import assert from "node:assert/strict";
import { calculatePirepScore, DEFAULT_SCORING_RULES, type ScoringEvent } from "./scoring.ts";
import { dispositionScore } from "./event-disposition.ts";
const policy = { id: "test", scopeKey: "GLOBAL", name: "test", version: 2, startingScore: 100, operationalWeight: 70, efficiencyWeight: 30, rules: DEFAULT_SCORING_RULES };
const event = (eventType: string, extra: Partial<ScoringEvent> = {}): ScoringEvent => ({ id: eventType, episodeId: eventType, eventType, status: "CONFIRMED", scoreEligible: true, ...extra });
const score = (events: ScoringEvent[]) => calculatePirepScore(policy, events, 80);
assert.equal(score([]).totalScore,94);
for (const [peak, penalty] of [[260,2],[267,4],[290,8],[310,12]]) assert.equal(score([event("OVERSPEED",{peakValue:peak,durationSeconds:60})]).operationalScore,100-penalty);
for (const [peak, penalty] of [[35,1],[37,3],[45,6],[55,10]]) assert.equal(score([event("TAXI_OVERSPEED",{peakValue:peak,durationSeconds:10})]).operationalScore,100-penalty);
const overspeed = event("OVERSPEED",{peakValue:267,durationSeconds:60});
assert.equal(score([overspeed, {...overspeed,id:"duplicate"}]).operationalScore,96);
assert.equal(score([event("OVERSPEED",{peakValue:267,durationSeconds:9})]).operationalScore,100);
assert.equal(score([{...overspeed,metadata:{atcHighSpeedAuthorized:true}}]).operationalScore,100);
assert.equal(score([{...overspeed,status:"DATA_QUALITY"}]).operationalScore,100);
assert.equal(score([{...overspeed,status:"DISMISSED"}]).operationalScore,100);
assert.equal(score([overspeed,{...overspeed,status:"DISMISSED"}]).operationalScore,100);
assert.equal(score([{...overspeed,status:"DISMISSED"},overspeed]).operationalScore,100);
const gear = {aircraftSnapshot:{GearPositionPercent:100,IsGearRetractable:true,IsOnGround:false}};
assert.equal(score([event("CLIMB_GEAR_LATE",{...gear,peakValue:2180,durationSeconds:13})]).operationalScore,99);
assert.equal(score([event("CLIMB_GEAR_LATE",{...gear,peakValue:2600,durationSeconds:13})]).operationalScore,97);
assert.equal(score([event("CLIMB_GEAR_LATE",{...gear,peakValue:5500,durationSeconds:65})]).requiresReview,true);
assert.equal(score([event("CRUISE_GEAR",{...gear,durationSeconds:10})]).operationalScore,92);
assert.equal(score([event("CRUISE_GEAR",{...gear,durationSeconds:65})]).operationalScore,88);
assert.equal(score([event("CRUISE_GEAR")]).operationalScore,100);
assert.equal(score([event("TAXI_OUT_FLAPS")]).operationalScore,100);
assert.equal(score([event("TAKEOFF_FLAPS")]).operationalScore,85);
assert.equal(score([event("TAKEOFF_FLAPS")]).requiresReview,true);
assert.equal(score(Array.from({length:20},(_,i)=>event("TAXI_OUT_BEACON_LIGHT",{id:`light${i}`,episodeId:`light${i}`}))).operationalScore,92);
for (const g of [1.2,1.03]) assert.equal(calculatePirepScore(policy,[],100,{landingG:g,landingRate:-200}).operationalScore,100);
const landing = event("LANDING_QUALITY",{metadata:{landingG:1.7,landingRate:-780}});
assert.equal(score([landing,landing,event("HARD_LANDING"),event("LANDING_G_EXTREME")]).operationalScore,85);
assert.equal(calculatePirepScore(policy,[{...landing,status:"DISMISSED"}],100,{landingG:2.1}).operationalScore,100);
assert.equal(score([event("GO_AROUND"),event("TELEMETRY_DROPOUT"),event("PAUSE")]).operationalScore,100);
assert.equal(dispositionScore(policy,[overspeed],"OVERSPEED","DISMISSED",80,{}).totalScore,94);
assert.equal(score([event("OVERSPEED",{peakValue:310,durationSeconds:60})]).requiresReview,true);
const bonus=score([overspeed,...Array.from({length:10},(_,i)=>event("STABLE_APPROACH",{episodeId:`bonus${i}`}))]);
assert.equal(bonus.operationalScore,100);
assert.equal((bonus.details as {positiveBonus:number}).positiveBonus,5);
console.log("FOQA v2 scoring and disposition regression tests passed");
assert.equal(score([event("CLIMB_GEAR_LATE",{...gear,peakValue:2000,durationSeconds:60})]).operationalScore,97);
const approach=(recovered=false):ScoringEvent=>event("UNSTABLE_APPROACH",{timestamp:"2026-08-27T18:00:00Z",durationSeconds:10,metadata:{minimumRadioAltitudeFeet:400,endReason:recovered?"Condition recovered":null}});
const outcome=(type:string)=>event(type,{timestamp:"2026-08-27T18:01:00Z",scoreEligible:false});
assert.equal(score([approach(),outcome("GO_AROUND")]).operationalScore,98);
assert.equal(score([approach(),outcome("LANDING")]).operationalScore,90);
assert.equal(score([approach(true),outcome("LANDING")]).operationalScore,98);
assert.equal(score([event("GEAR_OVERSPEED",{threshold:250,peakValue:254})]).operationalScore,95);
assert.equal(score([event("FLAP_OVERSPEED",{threshold:200,peakValue:216})]).operationalScore,85);
assert.equal(score([event("LOW_LANDING_FUEL",{threshold:1000,value:700})]).requiresReview,true);
const invalidationPolicy={...policy,rules:policy.rules.map(r=>r.code==="SLEW"?{...r,action:"INVALIDATE" as const}:r)};
assert.equal(calculatePirepScore(invalidationPolicy,[event("SLEW")],100).invalidated,true);

assert.equal(score([event("CLIMB_GEAR_LATE",{...gear,peakValue:1500,durationSeconds:30})]).operationalScore,100);
