export const DEFAULT_MIN_TURNAROUND_MINUTES = 45;
export const SCHEDULE_PROTECTION_BUFFER_MINUTES = 60;
export const SCHEDULE_DURATION_TOLERANCE_MINUTES = 5;
export const MAX_SCHEDULE_DURATION_MINUTES = 24 * 60;
export const MINUTES_PER_DAY = 24 * 60;
export const MINUTES_PER_WEEK = 7 * MINUTES_PER_DAY;
