import assert from "node:assert/strict";
import fs from "node:fs";
import { allocatePlannerLanes, buildPlannerWeek, isCurrentPlannerWeek, normalizeWeekStartUtc, plannerDraftPrefill, plannerRotationNeighbours, plannerValidationCell, reverseDraftSuggestion, roundPlannerMinutes, weekDates, type PlannerSchedule, type PlannerSegment } from "./planner.ts";

const d=(value:string)=>new Date(`${value}T00:00:00Z`);
const validation={valid:true,errors:[],warnings:[],days:[1,2,3,4,5,6,7].map(dayOfWeek=>({dayOfWeek,valid:true,issues:[]}))};
const schedule=(override:Partial<PlannerSchedule>={}):PlannerSchedule=>({id:"s1",code:"HFY101-AM",status:"DRAFT",daysOfWeek:[1],departureTimeMinutesUtc:480,scheduledDurationMinutes:60,effectiveFrom:d("2026-01-01"),effectiveUntil:null,route:{flightNumber:"HFY101",departure:"LEVC",arrival:"LEMD"},defaultFleet:{code:"A21N"},assignedAircraft:{registration:"EC-VLC"},validation,...override});
const week=(s:PlannerSchedule[],start="2026-08-03",includeExpired=false)=>buildPlannerWeek({weekStartUtc:d(start),schedules:s,includeExpired});
const segment=(key:string,startMinute:number,endMinute:number):PlannerSegment=>({key,scheduleId:key,flightId:null,flightStatus:null,dayOfWeek:1,operatingDate:d("2026-08-03"),startsAt:new Date(d("2026-08-03").getTime()+startMinute*60000),endsAt:new Date(d("2026-08-03").getTime()+endMinute*60000),startMinute,endMinute,continuation:"NONE",lane:0,laneCount:1,schedule:schedule({id:key})});

assert.equal(normalizeWeekStartUtc(new Date("2026-08-06T19:30:00Z")).toISOString(),"2026-08-03T00:00:00.000Z");
assert.deepEqual(weekDates(d("2026-08-03")).map(x=>x.toISOString().slice(0,10)),["2026-08-03","2026-08-04","2026-08-05","2026-08-06","2026-08-07","2026-08-08","2026-08-09"]);
assert.equal(weekDates(d("2026-08-31"))[1].toISOString().slice(0,10),"2026-09-01");
assert.equal(weekDates(d("2026-12-28"))[4].toISOString().slice(0,10),"2027-01-01");
assert.equal(weekDates(d("2024-02-26"))[3].toISOString().slice(0,10),"2024-02-29");
assert.equal(isCurrentPlannerWeek(d("2026-08-03"),new Date("2026-08-09T23:59:00Z")),true);
assert.equal(isCurrentPlannerWeek(d("2026-08-03"),d("2026-08-10")),false);
assert.equal(week([schedule()]).days[0].segments.length,1);
assert.equal(week([schedule({daysOfWeek:[1,2,3,4,5]})]).days.flatMap(x=>x.segments).length,5);
assert.equal(week([schedule({daysOfWeek:[1,2,3,4,5],effectiveFrom:d("2026-08-05")})]).days.flatMap(x=>x.segments).length,3);
assert.equal(week([schedule({daysOfWeek:[1,2,3,4,5],effectiveUntil:d("2026-08-05")})]).days.flatMap(x=>x.segments).length,3);
assert.equal(week([schedule({status:"DRAFT"})]).days[0].segments.length,1);
assert.equal(week([schedule({status:"ACTIVE"})]).days[0].segments.length,1);
assert.equal(week([schedule({status:"SUSPENDED"})]).days[0].segments.length,1);
assert.equal(week([schedule({status:"EXPIRED"})]).days[0].segments.length,0);
assert.equal(week([schedule({status:"ARCHIVED"})],"2026-08-03",true).days[0].segments.length,0);
assert.equal(week([schedule({status:"EXPIRED"})],"2026-08-03",true).days[0].segments.length,1);
assert.equal(week([schedule()]).days[0].segments[0].continuation,"NONE");
const overnight=week([schedule({departureTimeMinutesUtc:1410,scheduledDurationMinutes:105})]);
assert.equal(overnight.days[0].segments[0].continuation,"TO_NEXT_DAY");
assert.equal(overnight.days[1].segments[0].continuation,"FROM_PREVIOUS_DAY");
assert.equal(overnight.days[1].segments[0].scheduleId,"s1");
assert.equal(week([schedule({daysOfWeek:[7],departureTimeMinutesUtc:1410,scheduledDurationMinutes:105})]).days[6].segments.length,1,"Sunday fragment remains in selected week");
assert.equal(week([schedule({daysOfWeek:[7],departureTimeMinutesUtc:1410,scheduledDurationMinutes:105})],"2026-08-10").days[0].segments[0].continuation,"FROM_PREVIOUS_DAY");
assert.equal(week([schedule({daysOfWeek:[1],departureTimeMinutesUtc:1410,scheduledDurationMinutes:105})],"2026-08-31").days[1].operatingDate.toISOString().slice(0,10),"2026-09-01");
assert.equal(week([schedule({daysOfWeek:[4],departureTimeMinutesUtc:1410,scheduledDurationMinutes:105})],"2026-12-28").days[4].operatingDate.toISOString().slice(0,10),"2027-01-01");
assert.deepEqual(allocatePlannerLanes([segment("a",10,20),segment("b",20,30)]).map(x=>x.lane),[0,0]);
assert.deepEqual(allocatePlannerLanes([segment("a",10,30),segment("b",20,40)]).map(x=>x.lane),[0,1]);
assert.deepEqual(allocatePlannerLanes([segment("a",10,50),segment("b",20,40),segment("c",30,35)]).map(x=>x.lane),[0,1,2]);
assert.deepEqual(allocatePlannerLanes([segment("b",20,40),segment("a",10,30)]).map(x=>x.key),["a","b"]);
assert.equal(allocatePlannerLanes([segment("a",10,20)])[0].laneCount,1);
const generated=buildPlannerWeek({weekStartUtc:d("2026-08-03"),schedules:[schedule({status:"ACTIVE"})],flights:[{id:"f1",scheduleId:"s1",operatingDate:d("2026-08-03"),status:"BOOKED",generationKey:"schedule:s1:2026-08-03"}]});
assert.equal(generated.days[0].segments[0].flightId,"f1");
assert.equal(generated.days[0].segments[0].flightStatus,"BOOKED");
assert.equal(week([schedule({status:"ACTIVE"})]).days[0].segments[0].flightId,null);
assert.equal(buildPlannerWeek({weekStartUtc:d("2026-08-03"),schedules:[schedule({status:"ACTIVE"})],flights:[{id:"f2",scheduleId:"s1",operatingDate:d("2026-08-03"),status:"CANCELLED",generationKey:null}]}).days[0].segments[0].flightStatus,"CANCELLED");
assert.equal(week([schedule()]).days[0].segments[0].flightStatus,null);
assert.equal(plannerValidationCell(schedule({validation:{...validation,valid:false,errors:[{code:"E",severity:"ERROR",message:"e",dayOfWeek:1}],days:[{dayOfWeek:1,valid:false,issues:[{code:"E",severity:"ERROR",message:"e",dayOfWeek:1}]}]}}),1).state,"ERROR");
assert.equal(plannerValidationCell(schedule({validation:{...validation,warnings:[{code:"W",severity:"WARNING",message:"w",dayOfWeek:1}],days:[{dayOfWeek:1,valid:true,issues:[{code:"W",severity:"WARNING",message:"w",dayOfWeek:1}]}]}}),1).state,"WARNING");
assert.equal(plannerValidationCell(schedule(),1).state,"READY");
assert.equal(plannerValidationCell(schedule(),2).label,"—");
assert.equal(plannerValidationCell(schedule({validation:undefined}),1).state,"UNKNOWN");
const rotation=week([schedule({id:"a",departureTimeMinutesUtc:480}),schedule({id:"b",departureTimeMinutesUtc:600}),schedule({id:"c",departureTimeMinutesUtc:720})]).days[0].segments;
const neighbours=plannerRotationNeighbours(rotation[1],rotation);
assert.equal(neighbours.previous?.scheduleId,"a");assert.equal(neighbours.next?.scheduleId,"c");assert.equal(neighbours.minimumTurnaround,45);assert.equal(neighbours.availableTurnaround,60);assert.equal(neighbours.earliestNextDeparture.toISOString().slice(11,16),"11:45");
assert.equal(roundPlannerMinutes(482),480);assert.equal(roundPlannerMinutes(483),485);
const prefill=plannerDraftPrefill({aircraftId:"ac",fleetId:"fl",dayOfWeek:3,minute:483,operatingDate:d("2026-08-05")});
assert.equal(prefill.assignedAircraftId,"ac");assert.equal(prefill.defaultFleetId,"fl");assert.deepEqual(prefill.daysOfWeek,[3]);assert.equal(prefill.departureTimeMinutesUtc,485);assert.equal(prefill.effectiveFrom,"2026-08-05");
const reverse=reverseDraftSuggestion(schedule({daysOfWeek:[1,7],departureTimeMinutesUtc:1410,scheduledDurationMinutes:105}));assert.deepEqual(reverse.daysOfWeek,[2,1]);assert.equal(reverse.departure,"LEMD");assert.equal(reverse.arrival,"LEVC");assert.equal(reverse.departureTimeMinutesUtc,120);
const source=fs.readFileSync(new URL("../../components/programacion/weekly-planner.tsx",import.meta.url),"utf8"), actions=fs.readFileSync(new URL("../../app/staff/operations/programacion/actions.ts",import.meta.url),"utf8");
assert.match(source,/APLICAR DÍAS SELECCIONADOS/);assert.match(source,/CREAR REGRESO/);assert.match(actions,/SCHEDULE_EDIT/);for(const forbidden of ["flightOffer.create","pilotBooking.create","flightDispatch.create","ofpBriefing.create"])assert.doesNotMatch(actions,new RegExp(forbidden,"i"));
console.log("Programación weekly planner passed (62 focused assertions).");
