import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const read = (path: string) => readFileSync(fileURLToPath(new URL(path, import.meta.url)), "utf8");
const actions = read("../../app/staff/operations/programacion/actions.ts"), list = read("../../app/staff/operations/programacion/page.tsx"), detail = read("../../app/staff/operations/programacion/[id]/page.tsx"), edit = read("../../app/staff/operations/programacion/[id]/edit/page.tsx"), form = read("../../components/programacion/schedule-form.tsx"), navigation = read("../staff/navigation.ts");
const deleteForm = read("../../components/programacion/delete-programacion-form.tsx");
assert.match(actions, /requireStaffPermission\("SCHEDULE_CREATE"/);
assert.match(actions, /requireStaffPermission\("SCHEDULE_EDIT"/);
assert.match(actions, /requireStaffPermission\("SCHEDULE_STATUS_MANAGE"/);
assert.match(actions, /createFlightScheduleDraft/);
assert.match(actions, /updateFlightScheduleDraft/);
assert.match(actions, /duplicateFlightScheduleAsDraft/);
assert.match(actions, /archiveFlightScheduleDraft/);
assert.match(list, /Programación/);
assert.match(list, /validation/);
assert.match(detail, /ValidationIssues/);
assert.match(edit, /schedule\.status !== "DRAFT"/);
assert.match(form, /Comprobar programación/);
assert.doesNotMatch(form, /PUBLICAR|GENERAR FLIGHTS|ACTIVAR/i);
assert.match(navigation, /\/staff\/operations\/programacion/);
assert.match(actions, /deleteProgramacionAction[\s\S]*SCHEDULE_STATUS_MANAGE/);
assert.match(detail, /DeleteProgramacionForm/);
assert.match(deleteForm, /¿Seguro que deseas eliminar la programación/);
console.log("Programación staff routes and actions passed (14 focused assertions).");
