import assert from "node:assert/strict";
import fs from "node:fs";

const publication = fs.readFileSync(new URL("./publication.ts", import.meta.url), "utf8");
const generation = fs.readFileSync(new URL("./generation.ts", import.meta.url), "utf8");
const actions = fs.readFileSync(new URL("../../app/staff/operations/programacion/actions.ts", import.meta.url), "utf8");
const detail = fs.readFileSync(new URL("../../app/staff/operations/programacion/[id]/page.tsx", import.meta.url), "utf8");
const list = fs.readFileSync(new URL("../../app/staff/operations/programacion/page.tsx", import.meta.url), "utf8");
const booking = fs.readFileSync(new URL("../native-flight/booking.ts", import.meta.url), "utf8");
const prismaClient = fs.readFileSync(new URL("../prisma.ts", import.meta.url), "utf8");

for (const token of ["previewSchedulePublication", "publishFlightSchedule", "generateFlightsForSchedule", "topUpActiveSchedules", "SCHEDULE_PUBLISHED", "SCHEDULE_FLIGHTS_GENERATED"]) assert.match(publication, new RegExp(token));
assert.match(publication, /TransactionIsolationLevel\.Serializable/);
assert.match(publication, /pg_advisory_xact_lock/);
assert.match(publication, /schedule-publish:/);
assert.match(publication, /schedule-generation:/);
assert.match(publication, /current\.status !== "DRAFT"/);
assert.match(publication, /schedule\.status !== "ACTIVE"/);
assert.match(publication, /preview\.blockingIssues\.length/);
assert.match(publication, /warningFingerprint !== preview\.warningFingerprint/);
assert.match(publication, /status: "ACTIVE"/);
assert.match(publication, /alreadyPublished: true/);
assert.match(publication, /generationKey: candidate\.generationKey/);
assert.match(publication, /FLIGHT_NATURAL_KEY_CONFLICT/);
assert.match(publication, /existingKeys\.has/);
assert.match(publication, /generationKey: \{ in: keys \}/);
assert.match(publication, /dataOrigin: AocDataOrigin\.HISPAFLY_NATIVE/);
assert.match(publication, /operatingType: "SCHEDULED"/);
assert.match(publication, /NativeFlightStatus\.OPEN_FOR_BOOKING/);
assert.match(publication, /route\.departureAirport\.icao/);
assert.match(generation, /schedule:\$\{schedule\.id\}:\$\{isoDate\(operatingDate\)\}/);
assert.match(generation, /scheduledDeparture\.getTime\(\) \+ schedule\.scheduledDurationMinutes/);
assert.match(generation, /AIRPORT_TIMEZONE_FALLBACK_UTC/);
assert.match(generation, /DEPARTURE_ALREADY_PASSED/);
assert.match(generation, /BOOKING_WINDOW_ALREADY_CLOSED/);
assert.match(actions, /SCHEDULE_STATUS_MANAGE/g);
assert.match(detail, /PUBLICAR PROGRAMACIÓN/);
assert.match(detail, /AMPLIAR \/ ACTUALIZAR HORIZONTE/);
assert.match(detail, /He revisado y acepto las advertencias actuales/);
assert.doesNotMatch(list, /name="validation"/);
assert.match(booking, /NativeFlightStatus\.OPEN_FOR_BOOKING/);
assert.match(prismaClient, /transactionOptions/);
assert.match(prismaClient, /maxWait:\s*10_000/);
assert.match(prismaClient, /timeout:\s*60_000/);
for (const forbidden of ["flightOffer.create", "pilotBooking.create", "flightDispatch.create", "ofpBriefing.create", "acarsSession.create", "pirep.create"]) assert.doesNotMatch(publication, new RegExp(forbidden, "i"));
assert.doesNotMatch(publication, /self-dispatch|selfDispatch/);
console.log("Programación publication safety contracts passed (39 focused assertions).");
