"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

export type AirportTimelineMovement = { id:string; direction:"ARRIVAL"|"DEPARTURE"; flightNumber:string; departure:string; arrival:string; departureMinutesUtc:number; arrivalMinutesUtc:number; timeMinutesUtc:number; durationMinutes:number; fleet:string; status:string };
type PositionedMovement = AirportTimelineMovement & { lane:number; slotLoad:number };
const SLOT_MINUTES=15, MARKER_SEPARATION_MINUTES=54;
const fmt=(minutes:number)=>{const value=((Math.round(minutes)%1440)+1440)%1440;return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`};
const duration=(minutes:number)=>`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;
const slotStart=(minutes:number)=>Math.floor(minutes/SLOT_MINUTES)*SLOT_MINUTES;

function positionTrack(items:AirportTimelineMovement[],all:AirportTimelineMovement[]){const laneEnds:number[]=[];return [...items].sort((a,b)=>a.timeMinutesUtc-b.timeMinutesUtc||a.flightNumber.localeCompare(b.flightNumber)).map((item):PositionedMovement=>{let lane=laneEnds.findIndex(last=>item.timeMinutesUtc-last>=MARKER_SEPARATION_MINUTES);if(lane<0)lane=laneEnds.length;laneEnds[lane]=item.timeMinutesUtc;const start=slotStart(item.timeMinutesUtc);return{...item,lane,slotLoad:all.filter(candidate=>slotStart(candidate.timeMinutesUtc)===start).length}})}

function Facts({movement}:{movement:PositionedMovement}){const start=slotStart(movement.timeMinutesUtc);return <dl className="airport-timeline-facts"><div><dt>Route</dt><dd>{movement.departure} → {movement.arrival}</dd></div><div><dt>STD</dt><dd>{fmt(movement.departureMinutesUtc)} UTC</dd></div><div><dt>STA</dt><dd>{fmt(movement.arrivalMinutesUtc)} UTC</dd></div><div><dt>Fleet</dt><dd>{movement.fleet}</dd></div><div><dt>Duration</dt><dd>{duration(movement.durationMinutes)}</dd></div><div><dt>Movement</dt><dd>{movement.direction==="ARRIVAL"?"ARR":"DEP"}</dd></div><div><dt>Slot window</dt><dd>{fmt(start)}–{fmt(start+SLOT_MINUTES)}</dd></div><div><dt>Slot load</dt><dd>{movement.slotLoad} movement{movement.slotLoad===1?"":"s"}</dd></div></dl>}

function Marker({movement,selected,onSelect}:{movement:PositionedMovement;selected:boolean;onSelect:()=>void}){return <button type="button" className={`airport-timeline-marker ${movement.direction==="ARRIVAL"?"arrival":"departure"}${selected?" selected":""}`} style={{left:`${movement.timeMinutesUtc/1440*100}%`,top:`${14+movement.lane*38}px`}} aria-label={`${movement.flightNumber}, ${movement.direction.toLowerCase()} at ${fmt(movement.timeMinutesUtc)} UTC`} aria-pressed={selected} onClick={onSelect}><span className="airport-timeline-dot" aria-hidden="true"/><span className="airport-timeline-flight"><span className="airport-timeline-flight-full">{movement.flightNumber}</span><span className="airport-timeline-flight-short">{movement.flightNumber.replace(/^HF(?=\d)/i,"")}</span></span><span className="airport-timeline-tooltip" role="tooltip"><strong>{movement.flightNumber}</strong><span>{movement.departure} → {movement.arrival}</span><Facts movement={movement}/><span className={`airport-timeline-status ${movement.status.toLowerCase()}`}>● {movement.status}</span></span></button>}

export function AirportMovementTimeline({movements}:{movements:AirportTimelineMovement[]}){
 const positioned=useMemo(()=>({arrivals:positionTrack(movements.filter(x=>x.direction==="ARRIVAL"),movements),departures:positionTrack(movements.filter(x=>x.direction==="DEPARTURE"),movements)}),[movements]);
 const all=[...positioned.arrivals,...positioned.departures]; const [selectedId,setSelectedId]=useState<string|null>(null); const selected=all.find(x=>`${x.direction}-${x.id}`===selectedId)??null;
 return <section className="card airport-timeline-card" aria-label="Airport movement timeline"><header className="airport-timeline-header"><div><h2>Airport Movement Timeline</h2><p>ARR y DEP · escala compartida de 24 horas · UTC</p></div><span>UTC</span></header>{!movements.length?<div className="airport-board-empty">No hay slots para esta fecha.</div>:<div className="airport-timeline-scroll"><div className="airport-timeline-board"><div className="airport-timeline-axis">{[0,3,6,9,12,15,18,21,24].map(hour=><span key={hour} style={{left:`${hour/24*100}%`}}>{String(hour).padStart(2,"0")}:00</span>)}</div>{(["DEPARTURE","ARRIVAL"] as const).map(direction=>{const track=direction==="ARRIVAL"?positioned.arrivals:positioned.departures;const lanes=Math.max(1,...track.map(x=>x.lane+1));return <div className="airport-timeline-track-row" key={direction}><strong className={`airport-timeline-track-label ${direction.toLowerCase()}`}>{direction==="ARRIVAL"?"ARR":"DEP"}</strong><div className="airport-timeline-track" style={{height:`${Math.max(72,lanes*38+30)}px`}}><div className="airport-timeline-grid" aria-hidden="true"/>{track.map(movement=><Marker key={`${movement.direction}-${movement.id}`} movement={movement} selected={`${movement.direction}-${movement.id}`===selectedId} onSelect={()=>setSelectedId(`${movement.direction}-${movement.id}`)}/>)}</div></div>})}</div></div>}<div className={`airport-timeline-details${selected?" visible":""}`} aria-live="polite">{selected?<><div className="airport-timeline-details-heading"><div><span>SELECTED MOVEMENT</span><h3>{selected.flightNumber}</h3><p>{selected.departure} → {selected.arrival}</p></div><span className={`airport-timeline-status ${selected.status.toLowerCase()}`}>● {selected.status}</span></div><Facts movement={selected}/><div className="airport-timeline-details-actions"><button type="button" className="button secondary" onClick={()=>setSelectedId(null)}>CERRAR</button><Link className="button" href={`/staff/operations/programacion/${selected.id}`}>ABRIR PROGRAMACIÓN</Link></div></>:<p>Selecciona un vuelo para mantener sus detalles visibles.</p>}</div></section>
}
