"use client";
import { useMemo, useState, type ReactNode } from "react";
import Link from "next/link";
import type { ScheduleValidationResult } from "@/lib/native-scheduling/types";
import type { ProgramacionAircraftOption, ProgramacionFleetOption, ProgramacionFormValue, ProgramacionRouteOption } from "./types";

const hhmm = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;
const fromTime = (value: string) => { const [hour, minute] = value.split(":").map(Number); return hour * 60 + minute; };
const labels = ["L", "M", "X", "J", "V", "S", "D"];

export function ScheduleForm({ action, value = {}, routes, fleets, aircraft, submitLabel, cancelHref = "/staff/operations/programacion", hiddenFields = {}, rotationContext }: { action: (form: FormData) => void | Promise<void>; value?: ProgramacionFormValue; routes: ProgramacionRouteOption[]; fleets: ProgramacionFleetOption[]; aircraft: ProgramacionAircraftOption[]; submitLabel: string; cancelHref?: string; hiddenFields?: Record<string, string>; rotationContext?: ReactNode }) {
  const [routeId, setRouteId] = useState(value.routeId ?? ""), [fleetId, setFleetId] = useState(value.defaultFleetId ?? ""), [days, setDays] = useState(value.daysOfWeek ?? []), [departure, setDeparture] = useState(value.departureTimeMinutesUtc ?? 480), [duration, setDuration] = useState(value.scheduledDurationMinutes ?? 60), [validation, setValidation] = useState<ScheduleValidationResult | null>(null), [checking, setChecking] = useState(false), [checkError, setCheckError] = useState("");
  const route = routes.find((item) => item.id === routeId), arrival = (departure + duration) % 1440, nextDay = departure + duration >= 1440;
  const compatibleFleets = route ? fleets.filter((item) => route.compatibleFleetIds.includes(item.id)).map((item) => item.label).join(", ") || "Cualquier flota no prohibida" : "—";
  const availableAircraft = useMemo(() => aircraft.filter((item) => !fleetId || item.fleetId === fleetId), [aircraft, fleetId]);
  const validate = async () => { setChecking(true); setCheckError(""); try { const response = await fetch("/api/staff/operations/flight-schedules/validate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scheduleId: value.id, routeId, daysOfWeek: days, departureTimeMinutesUtc: departure, arrivalTimeMinutesUtc: arrival, scheduledDurationMinutes: duration, defaultFleetId: fleetId || null, assignedAircraftId: (document.querySelector('[name="assignedAircraftId"]') as HTMLSelectElement | null)?.value || null, effectiveFrom: `${(document.querySelector('[name="effectiveFrom"]') as HTMLInputElement)?.value}T00:00:00.000Z`, effectiveUntil: (document.querySelector('[name="effectiveUntil"]') as HTMLInputElement)?.value ? `${(document.querySelector('[name="effectiveUntil"]') as HTMLInputElement).value}T00:00:00.000Z` : null }) }); if (!response.ok) throw new Error((await response.json()).error ?? "No se pudo validar."); setValidation(await response.json()); } catch (error) { setCheckError(error instanceof Error ? error.message : "No se pudo validar."); } finally { setChecking(false); } };
  return <form action={action} className="programacion-form">
    {value.id && <input type="hidden" name="id" value={value.id}/>}<input type="hidden" name="departureTimeMinutesUtc" value={departure}/>{Object.entries(hiddenFields).map(([name, fieldValue]) => <input key={name} type="hidden" name={name} value={fieldValue}/>)}
    <fieldset><legend>Identidad y ruta</legend><div className="form-grid"><label>Código<input name="code" required defaultValue={value.code}/></label><label>Descripción interna<input name="name" defaultValue={value.name ?? ""}/></label><label className="programacion-wide">Ruta<select name="routeId" required value={routeId} onChange={(event) => { const selected = routes.find((item) => item.id === event.target.value); setRouteId(event.target.value); if (selected?.defaultFleetId) setFleetId(selected.defaultFleetId); if (selected?.duration) setDuration(selected.duration); }}><option value="">Selecciona una ruta</option>{routes.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div>{route && <div className="programacion-route-summary"><span>Vuelo <strong>{route.flightNumber ?? "—"}</strong></span><span>Callsign <strong>{route.callsign ?? "—"}</strong></span><span>Trayecto <strong>{route.departure} → {route.arrival}</strong></span><span>Duración base <strong>{route.duration ? hhmm(route.duration) : "—"}</strong></span><span>Flotas compatibles <strong>{compatibleFleets}</strong></span></div>}</fieldset>
    <fieldset><legend>Días y horario UTC</legend><div className="programacion-days">{labels.map((label, index) => { const day = index + 1; return <label className={days.includes(day) ? "selected" : ""} key={day}><input type="checkbox" name="daysOfWeek" value={day} checked={days.includes(day)} onChange={() => setDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day].sort())}/><span>{label}</span></label>; })}</div><div className="form-grid"><label>Salida UTC<input type="time" required value={hhmm(departure)} onChange={(event) => setDeparture(fromTime(event.target.value))}/></label><label>Duración (minutos)<input name="scheduledDurationMinutes" type="number" min="1" max="1440" required value={duration} onChange={(event) => setDuration(Number(event.target.value))}/></label><div className="programacion-arrival"><span>Llegada UTC</span><strong>{hhmm(arrival)}{nextDay ? " (+1 día)" : ""}</strong></div></div></fieldset>
    <fieldset><legend>Flota y aeronave</legend><div className="form-grid"><label>Flota requerida<select name="defaultFleetId" value={fleetId} onChange={(event) => setFleetId(event.target.value)}><option value="">Sin flota fija</option>{fleets.map((item) => <option key={item.id} value={item.id}>{item.label} · {item.status}</option>)}</select></label><label>Aeronave asignada (opcional)<select name="assignedAircraftId" defaultValue={value.assignedAircraftId ?? ""}><option value="">Sin asignar</option>{availableAircraft.map((item) => <option key={item.id} value={item.id}>{item.registration} · {item.type} · {item.status}{item.airport ? ` · ${item.airport}` : ""}</option>)}</select></label></div></fieldset>
    <fieldset><legend>Vigencia y configuración</legend><div className="form-grid"><label>Válido desde<input name="effectiveFrom" type="date" required defaultValue={value.effectiveFrom}/></label><label>Válido hasta<input name="effectiveUntil" type="date" defaultValue={value.effectiveUntil}/></label><label>Reservas abren antes (min)<input name="bookingOpenOffsetMinutes" type="number" min="0" defaultValue={value.bookingOpenOffsetMinutes ?? 10080}/></label><label>Reservas cierran antes (min)<input name="bookingCloseOffsetMinutes" type="number" min="0" defaultValue={value.bookingCloseOffsetMinutes ?? 60}/></label><label>Horizonte de generación (días)<input name="generationHorizonDays" type="number" min="1" max="365" defaultValue={value.generationHorizonDays ?? 30}/></label><label className="programacion-wide">Notas<textarea name="notes" defaultValue={value.notes ?? ""}/></label></div></fieldset>
    {rotationContext}
    {(validation || checkError) && <div className={`programacion-check ${validation?.valid ? "valid" : "invalid"}`}><strong>{checkError || (validation ? `${validation.valid ? "Programación válida" : `${validation.errors.length} conflictos`} · ${validation.warnings.length} advertencias` : "")}</strong>{validation && [...validation.errors, ...validation.warnings].length > 0 && <ul>{[...validation.errors, ...validation.warnings].map((item, index) => <li key={`${item.code}-${index}`}><b>{item.code}</b> — {item.message}</li>)}</ul>}</div>}
    <div className="button-row"><button type="button" className="button secondary" disabled={checking} onClick={validate}>{checking ? "Comprobando…" : "Comprobar programación"}</button><button className="button">{submitLabel}</button><Link href={cancelHref}>Cancelar</Link></div>
  </form>;
}
