"use client";
import { useState } from "react";
import Link from "next/link";
import { plannerRotationNeighbours, plannerValidationCell, reverseDraftSuggestion, type PlannerSchedule, type PlannerWeek } from "@/lib/native-scheduling/planner";
import { applyPlannerDaysAction } from "@/app/staff/operations/programacion/actions";

const dayNames = ["", "LUN", "MAR", "MIÉ", "JUE", "VIE", "SÁB", "DOM"];
const hhmm = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2,"0")}:${String(minutes % 60).padStart(2,"0")}`;
const iso = (date: Date) => new Date(date).toISOString().slice(0,10);
const statusClass = (schedule: PlannerSchedule) => { const errors = schedule.validation?.errors.length ?? 0, warnings = schedule.validation?.warnings.length ?? 0; return `${schedule.status.toLowerCase()} ${errors ? "has-errors" : warnings ? "has-warnings" : "is-valid"}`; };

export function WeeklyPlanner({ week, schedules, aircraftId, fleetId, canCreate, canEdit, initialScheduleId }: { week: PlannerWeek; schedules: PlannerSchedule[]; aircraftId: string; fleetId?: string | null; canCreate: boolean; canEdit: boolean; initialScheduleId?: string }) {
  const [selectedId, setSelectedId] = useState(initialScheduleId ?? schedules[0]?.id ?? "");
  const selected = schedules.find(({ id }) => id === selectedId) ?? schedules[0];
  const allSegments = week.days.flatMap(({ segments }) => segments);
  const selectedSegment = allSegments.find(({ scheduleId }) => scheduleId === selected?.id);
  const neighbours = selectedSegment ? plannerRotationNeighbours(selectedSegment, allSegments) : null;
  const reverse = selected ? reverseDraftSuggestion(selected) : null;
  const createAt = (event: React.MouseEvent<HTMLDivElement>, dayOfWeek: number, operatingDate: Date) => { if (!canCreate || (event.target as HTMLElement).closest("a,button")) return; const rect = event.currentTarget.getBoundingClientRect(); const minute = Math.round(((event.clientX - rect.left) / rect.width) * 1440 / 5) * 5; const query = new URLSearchParams({ view: "planner", panel: "schedule", mode: "create", aircraftId, defaultFleetId: fleetId ?? "", daysOfWeek: String(dayOfWeek), departureTimeMinutesUtc: String(Math.min(1435, Math.max(0, minute))), effectiveFrom: iso(operatingDate), week: iso(week.startUtc) }); window.location.assign(`/staff/operations/programacion?${query}`); };
  const utilization = [...new Map(allSegments.map((segment)=>[`${segment.scheduleId}:${segment.key.split(":")[1]}`,segment.schedule.scheduledDurationMinutes])).values()].reduce((a,b)=>a+b,0);
  const errors = schedules.reduce((sum, item) => sum + (item.validation?.errors.length ?? 0), 0), warnings = schedules.reduce((sum, item) => sum + (item.validation?.warnings.length ?? 0), 0);
  return <div className="weekly-planner">
    <section className="planner-summary"><div><span>ROTACIÓN</span><strong>{aircraftId === "unassigned" ? "SIN AERONAVE" : schedules[0]?.assignedAircraft?.registration ?? "AERONAVE"}</strong></div><div><strong>{allSegments.length}</strong><span>fragmentos visibles</span></div><div><strong className={errors ? "danger-text" : ""}>{errors}</strong><span>conflictos</span></div><div><strong>{warnings}</strong><span>advertencias</span></div><div><strong>{Math.floor(utilization/60)} h {utilization%60} min</strong><span>programadas</span></div><div><strong>{(utilization/10080*100).toFixed(1)} %</strong><span>utilización semanal</span></div></section>
    {selected && <section className="planner-inspector card"><div className="planner-inspector-head"><div><span className="eyebrow">SEGMENTO SELECCIONADO</span><h2>{selected.route.flightNumber ?? selected.code} · {selected.route.departure} → {selected.route.arrival}</h2><p>{selected.assignedAircraft?.registration ?? "Sin aeronave"} · {selected.defaultFleet?.code ?? "Flota libre"} · Schedule: <b>{selected.status}</b>{selectedSegment?.flightStatus && <> · Flight: <b>{selectedSegment.flightStatus}</b></>}</p></div><div className="button-row"><Link href={`/staff/operations/programacion/${selected.id}`}>ABRIR DETALLE</Link>{selected.status === "DRAFT" && canEdit && <Link className="button secondary" href={`/staff/operations/programacion?view=planner&panel=schedule&mode=edit&scheduleId=${selected.id}&week=${iso(week.startUtc)}&aircraftId=${aircraftId}`}>EDITAR BORRADOR</Link>}{selected.status === "DRAFT" && canCreate && reverse && <Link className="button" href={`/staff/operations/programacion?view=planner&panel=schedule&mode=create&reverseOf=${selected.id}&departure=${reverse.departure}&arrival=${reverse.arrival}&daysOfWeek=${reverse.daysOfWeek.join(",")}&departureTimeMinutesUtc=${reverse.departureTimeMinutesUtc}&code=${reverse.code}&aircraftId=${aircraftId}&defaultFleetId=${fleetId ?? ""}&week=${iso(week.startUtc)}&effectiveFrom=${iso(week.startUtc)}&effectiveUntil=${iso(week.endUtc)}`}>CREAR REGRESO</Link>}</div></div>
      <div className="planner-matrix-wrap"><table className="planner-matrix"><thead><tr><th>Comprobación</th>{week.days.map((day) => <th key={day.dayOfWeek}>{dayNames[day.dayOfWeek]}<small>{new Date(day.operatingDate).getUTCDate()}</small></th>)}</tr></thead><tbody><tr><th>Opera</th>{week.days.map((day) => { const cell=plannerValidationCell(selected,day.dayOfWeek); return <td key={day.dayOfWeek} className={`matrix-${cell.state.toLowerCase()}`} title={cell.issues.map((i)=>i.message).join("\n")}>{cell.label}</td>; })}</tr><tr><th>Salida UTC</th>{week.days.map((day)=><td key={day.dayOfWeek}>{selected.daysOfWeek.includes(day.dayOfWeek)?hhmm(selected.departureTimeMinutesUtc):"—"}</td>)}</tr><tr><th>Llegada UTC</th>{week.days.map((day)=><td key={day.dayOfWeek}>{selected.daysOfWeek.includes(day.dayOfWeek)?hhmm((selected.departureTimeMinutesUtc+selected.scheduledDurationMinutes)%1440):"—"}</td>)}</tr><tr><th>Vuelo generado</th>{week.days.map((day)=>{const segment=day.segments.find((item)=>item.scheduleId===selected.id);return <td key={day.dayOfWeek}>{segment?.flightId?"✓":"—"}</td>})}</tr></tbody></table></div>
      {neighbours && <div className="planner-neighbours"><span>Anterior <b>{neighbours.previous?.schedule.route.flightNumber ?? "—"}</b></span><span>Siguiente <b>{neighbours.next?.schedule.route.flightNumber ?? "—"}</b></span><span>Turnaround disponible <b>{neighbours.availableTurnaround ?? "—"} min</b></span><span>Mínimo <b>{neighbours.minimumTurnaround} min</b></span><span>Próxima salida posible <b>{neighbours.earliestNextDeparture.toISOString().slice(11,16)} UTC</b></span></div>}
      {selected.status==="DRAFT"&&canEdit&&<form key={selected.id} action={applyPlannerDaysAction} className="planner-apply-days"><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="aircraftId" value={aircraftId}/><input type="hidden" name="week" value={iso(week.startUtc)}/>{["L","M","X","J","V","S","D"].map((label,index)=>{const day=index+1;return <label className={selected.daysOfWeek.includes(day)?"selected":""} key={day}><input name="daysOfWeek" type="checkbox" value={day} defaultChecked={selected.daysOfWeek.includes(day)}/><span>{label}</span></label>})}<button className="button secondary">APLICAR DÍAS SELECCIONADOS</button></form>}
    </section>}
    <section className="planner-board card"><div className="planner-axis"><div className="planner-day-label">DÍA / UTC</div><div className="planner-hours">{Array.from({length:24},(_,hour)=><span key={hour} style={{left:`${hour/24*100}%`}}>{String(hour).padStart(2,"0")}</span>)}</div></div>{week.days.map((day)=><div className="planner-day" key={day.dayOfWeek} style={{minHeight:`${Math.max(72,day.laneCount*62+16)}px`}}><div className="planner-day-label"><b>{dayNames[day.dayOfWeek]}</b><span>{new Date(day.operatingDate).toLocaleDateString("es-ES",{day:"2-digit",month:"short",timeZone:"UTC"}).toUpperCase()}</span></div><div className="planner-track" role="button" tabIndex={canCreate?0:-1} aria-label={`Crear borrador el ${iso(day.operatingDate)}`} onClick={(event)=>createAt(event,day.dayOfWeek,day.operatingDate)}>{day.segments.map((segment)=><button key={segment.key} className={`planner-block ${statusClass(segment.schedule)} lane-${segment.lane}`} style={{left:`${segment.startMinute/1440*100}%`,width:`${Math.max((segment.endMinute-segment.startMinute)/1440*100,.45)}%`,top:`${8+segment.lane*58}px`}} onClick={(event)=>{event.stopPropagation();setSelectedId(segment.scheduleId)}} title={`${segment.schedule.code} · ${segment.schedule.route.flightNumber ?? "Sin número"}\n${segment.schedule.route.departure} → ${segment.schedule.route.arrival}\n${hhmm(segment.schedule.departureTimeMinutesUtc)}–${hhmm((segment.schedule.departureTimeMinutesUtc+segment.schedule.scheduledDurationMinutes)%1440)} UTC\n${segment.schedule.status}${segment.flightStatus?` · Flight ${segment.flightStatus}`:""}`} aria-label={`Seleccionar ${segment.schedule.code}, ${segment.schedule.route.departure} a ${segment.schedule.route.arrival}`}><b>{segment.continuation==="FROM_PREVIOUS_DAY"?"→ ":""}{segment.schedule.route.flightNumber?.replace(/^HFY/,"") ?? segment.schedule.code}</b><span>{segment.schedule.route.departure}–{segment.schedule.route.arrival}</span><small>{hhmm(segment.startMinute)}–{segment.endMinute===1440?"24:00":hhmm(segment.endMinute)}</small>{segment.flightStatus&&<em>{segment.flightStatus.replaceAll("_"," ")}</em>}{segment.continuation==="TO_NEXT_DAY"&&<i>→</i>}</button>)}</div></div>)}</section>
  </div>;
}
