import type {StaffPermissionCode} from "./access/catalog.ts";export type StaffNavigationItem={key:string;labelKey:string;href:string;permission:StaffPermissionCode;match?:string};export type StaffNavigationGroup={key:string;labelKey:string;items:StaffNavigationItem[]};
export const STAFF_NAVIGATION:StaffNavigationGroup[]=[
{key:"overview",labelKey:"staffNav.groups.overview",items:[{key:"dashboard",labelKey:"staffNav.dashboard",href:"/staff",permission:"DASHBOARD_VIEW"}]},
{key:"operations",labelKey:"staffNav.groups.operations",items:[{key:"offers",labelKey:"staffNav.offers",href:"/staff/flight-offers",permission:"FLIGHT_OFFER_VIEW"},{key:"ofp",labelKey:"staffNav.ofp",href:"/staff/ofp",permission:"OFP_VIEW"},{key:"pireps",labelKey:"staffNav.pireps",href:"/staff/pireps",permission:"PIREP_VIEW"},{key:"fuelPolicy",labelKey:"staffNav.fuelPolicy",href:"/staff/fuel-policy",permission:"FUEL_POLICY_VIEW"}]},
{key:"network",labelKey:"staffNav.groups.network",items:[{key:"airports",labelKey:"staffNav.airports",href:"/staff/airports",permission:"AIRPORT_VIEW"},{key:"routes",labelKey:"staffNav.routes",href:"/staff/routes",permission:"ROUTE_VIEW"},{key:"schedules",labelKey:"staffNav.schedules",href:"/staff/schedules",permission:"SCHEDULE_VIEW"},{key:"flights",labelKey:"staffNav.flights",href:"/staff/flights",permission:"FLIGHT_VIEW"}]},
{key:"fleetEngineering",labelKey:"staffNav.groups.fleetEngineering",items:[{key:"fleets",labelKey:"staffNav.fleetOverview",href:"/staff/fleets",permission:"FLEET_VIEW"},{key:"aircraft",labelKey:"staffNav.aircraft",href:"/staff/aircraft",permission:"AIRCRAFT_VIEW"},{key:"fleet",labelKey:"staffNav.aircraftLocations",href:"/staff/fleet",permission:"FLEET_LOCATION_VIEW"},{key:"performance",labelKey:"staffNav.performance",href:"/staff/fleet-performance",permission:"AIRCRAFT_PERFORMANCE_VIEW"}]},
{key:"crew",labelKey:"staffNav.groups.crew",items:[{key:"pilots",labelKey:"staffNav.pilots",href:"/staff/pilots",permission:"PILOT_VIEW"}]},
{key:"finance",labelKey:"staffNav.groups.finance",items:[{key:"economy",labelKey:"staffNav.economyOverview",href:"/staff/wallet",permission:"ECONOMY_VIEW"},{key:"expenses",labelKey:"staffNav.expensesShort",href:"/staff/expenses",permission:"EXPENSE_VIEW"},{key:"expenseRules",labelKey:"staffNav.expenseRules",href:"/staff/expenses/rules",permission:"EXPENSE_RULE_VIEW"},{key:"payroll",labelKey:"staffNav.payroll",href:"/staff/payroll",permission:"PAYROLL_VIEW"}]},
{key:"administration",labelKey:"staffNav.groups.administration",items:[{key:"staffPermissions",labelKey:"staffNav.staffPermissions",href:"/staff/admin/users",permission:"STAFF_VIEW"},{key:"audit",labelKey:"staffNav.audit",href:"/staff/audit",permission:"AUDIT_LOG_VIEW"},{key:"vamsys",labelKey:"staffNav.integrations",href:"/staff/settings/vamsys",permission:"VAMSYS_CONNECTION_VIEW"},{key:"operationsApi",labelKey:"staffNav.apiSync",href:"/staff/settings/operations",permission:"OPERATIONS_API_VIEW"},{key:"settings",labelKey:"staffNav.systemSettings",href:"/staff/settings",permission:"SYSTEM_SETTINGS_VIEW"}]}
];
export function visibleNavigation(permissions:ReadonlySet<string>){return STAFF_NAVIGATION.map(g=>({...g,items:g.items.filter(i=>permissions.has(i.permission))})).filter(g=>g.items.length)}
