import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getFlightSchedule } from "@/lib/native-scheduling/repository";
import { validateProposedSchedule } from "@/lib/native-scheduling/service";
import { formatDate, formatDays, formatDuration, formatMinutes, toProposedSchedule } from "@/lib/native-scheduling/presentation";
import { ValidationIssues } from "@/components/programacion/validation-issues";
import { getCurrentStaff } from "@/lib/staff/currentStaff";
import { staffHasPermission } from "@/lib/staff/permissions";
import { archiveProgramacionAction, duplicateProgramacionAction } from "../actions";
export default async function ProgramacionDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string; duplicated?: string }> }) { const [{ id }, query, staff] = await Promise.all([params, searchParams, getCurrentStaff()]); const schedule = await getFlightSchedule(id); if (!schedule) notFound(); const [validation, audit] = await Promise.all([validateProposedSchedule(toProposedSchedule(schedule), { excludeScheduleId: id }), prisma.aocAuditLog.findMany({ where: { entityType: "FlightSchedule", entityId: id }, orderBy: { createdAt: "desc" }, take: 10 })]); return <><div className="page-header"><div><div className="eyebrow">PROGRAMACIÓN</div><h1>{schedule.code}</h1><p>{schedule.name ?? `${schedule.route.departure} → ${schedule.route.arrival}`}</p></div><div className="button-row"><Link href="/staff/operations/programacion">Volver</Link>{schedule.status === "DRAFT" && staffHasPermission(staff, "SCHEDULE_EDIT") && <Link className="button" href={`/staff/operations/programacion/${id}/edit`}>Editar borrador</Link>}</div></div>{query.error && <div className="notice">{query.error}</div>}{query.saved && <div className="notice">Borrador guardado. Validación actualizada.</div>}{query.duplicated && <div className="notice">Borrador duplicado correctamente.</div>}
  <section className="card programacion-detail"><div className="workflow-summary"><div><span>Ruta</span><strong>{schedule.route.departure} → {schedule.route.arrival}</strong></div><div><span>Vuelo / Callsign</span><strong>{schedule.route.flightNumber ?? "—"} / {schedule.route.callsign ?? "—"}</strong></div><div><span>Días</span><strong>{formatDays(schedule.daysOfWeek)}</strong></div><div><span>Horario UTC</span><strong>{formatMinutes(schedule.departureTimeMinutesUtc)} → {formatMinutes(schedule.arrivalTimeMinutesUtc)}</strong></div><div><span>Duración</span><strong>{formatDuration(schedule.scheduledDurationMinutes)}</strong></div><div><span>Flota</span><strong>{schedule.defaultFleet?.code ?? "Libre"}</strong></div><div><span>Aeronave</span><strong>{schedule.assignedAircraft?.registration ?? "Sin asignar"}</strong></div><div><span>Vigencia</span><strong>{formatDate(schedule.effectiveFrom)} → {formatDate(schedule.effectiveUntil)}</strong></div><div><span>Estado</span><strong>{schedule.status}</strong></div><div><span>Flights relacionados</span><strong>{schedule._count.flights}</strong></div><div><span>Reservas</span><strong>{schedule.bookingOpenOffsetMinutes} / {schedule.bookingCloseOffsetMinutes} min</strong></div><div><span>Horizonte</span><strong>{schedule.generationHorizonDays} días</strong></div></div>{schedule.notes && <p>{schedule.notes}</p>}</section>
  <section className="card"><ValidationIssues result={validation}/></section>
  <section className="programacion-actions-grid">{staffHasPermission(staff, "SCHEDULE_CREATE") && <form action={duplicateProgramacionAction} className="card"><h2>Duplicar como borrador</h2><input type="hidden" name="id" value={id}/><label>Nuevo código<input name="code" required defaultValue={`${schedule.code}-COPY`}/></label><label>Válido desde<input name="effectiveFrom" type="date" required defaultValue={schedule.effectiveFrom.toISOString().slice(0,10)}/></label><label>Válido hasta<input name="effectiveUntil" type="date" defaultValue={schedule.effectiveUntil?.toISOString().slice(0,10)}/></label><button className="button secondary">Duplicar</button></form>}{schedule.status === "DRAFT" && staffHasPermission(staff, "SCHEDULE_STATUS_MANAGE") && <form action={archiveProgramacionAction} className="card"><h2>Archivar borrador</h2><p className="meta">El registro se conservará y no se eliminará.</p><input type="hidden" name="id" value={id}/><button className="button secondary">Archivar</button></form>}</section>
  <section className="card"><h2>Auditoría</h2>{audit.length ? <div className="programacion-audit">{audit.map((item) => <div key={item.id}><strong>{item.action}</strong><span>{item.message}</span><time>{item.createdAt.toLocaleString("es-ES")}</time></div>)}</div> : <p className="meta">Sin actividad registrada.</p>}</section></>; }
