import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentPilot } from "@/lib/pilot/session";
import { loginPilot } from "./actions";
const messages:Record<string,string>={invalid_credentials:"Email or password is incorrect, or the account is locked.",login_required:"Please sign in to continue."};
export default async function PilotPortal({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
  const [q,pilot]=await Promise.all([searchParams,getCurrentPilot()]);if(pilot)redirect("/pilot/dashboard");
  return <div className="pilot-shell"><header className="pilot-header"><Link href="/" className="pilot-logo"><Image src="/logo-hispafly-full.png" alt="HISPAFLY" width={1800} height={400} priority/></Link><nav><Link href="/">Switch portal</Link></nav></header><main className="pilot-content"><div className="pilot-hero"><p>PILOT PORTAL</p><h1>Your flying life,<br/>all in one place.</h1><span>Sign in with your independent Hispafly pilot account.</span></div>{q.success&&<div className="feedback success">{q.success==="logged_out"?"You have been signed out.":q.success==="check_email"?"Account created. Check your email to activate it.":q.success==="password_reset"?"Password updated. You can now sign in.":q.success}</div>}{q.error&&<div className="feedback error">{messages[q.error]??q.error}</div>}<section className="pilot-welcome-card"><div><small>HISPAFLY IDENTITY</small><h2>Pilot sign in</h2><p>Your account, sessions and pilot profile are stored exclusively by Hispafly.</p><div className="login-actions"><Link href="/register">Create account</Link><Link href="/forgot-password">Forgot password?</Link></div></div><form className="login-form" action={loginPilot}><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required minLength={12}/></label><div className="login-actions"><button className="button">SIGN IN</button></div></form></section></main></div>;
}
