"use client";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import type { LiveFlight, TrackPoint } from "./types";
const LiveMap=dynamic(()=>import("./live-map"),{ssr:false,loading:()=> <div className="fleet-map-loading"/>});
export function LiveOperations({initialFlights}:{initialFlights:LiveFlight[]}){
 const [flights,setFlights]=useState(initialFlights),[selected,setSelected]=useState<string|null>(initialFlights[0]?.id??null),[track,setTrack]=useState<TrackPoint[]>([]),[updated,setUpdated]=useState(new Date().toISOString());
 useEffect(()=>{const load=async()=>{const r=await fetch("/api/staff/live-flights",{cache:"no-store"});if(r.ok){const b=await r.json();setFlights(b.flights);setUpdated(b.updatedAt)}};const timer=setInterval(load,10000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!selected)return;const load=()=>fetch(`/api/staff/live-flights/${selected}/track`,{cache:"no-store"}).then(r=>r.ok?r.json():null).then(b=>b&&setTrack(b.points));void load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[selected]);
 const active=useMemo(()=>flights.filter(x=>x.sessionStatus==="ACTIVE"),[flights]),online=active.filter(x=>x.connectionStatus==="ONLINE").length,delayed=active.filter(x=>x.connectionStatus==="DELAYED").length,offline=active.filter(x=>x.connectionStatus==="OFFLINE").length;
 return <><div className="page-header"><div><div className="eyebrow">OPERATIONS CONTROL</div><h1>Live flights</h1><p>Native ACARS position, phase and connection monitoring.</p></div><span className="meta">Updated {new Date(updated).toLocaleTimeString()}</span></div>
 <div className="grid stats live-kpis">{[["Active",active.length,"blue"],["Online",online,""],["Delayed",delayed,"amber"],["Offline",offline,"red"]].map(([label,value,color])=><div className="card" key={label}><div className="stat-label">{label}</div><div className="stat-value">{value}</div><span className={`badge ${color}`}>{label}</span></div>)}</div>
 <section className="card live-map-card"><div className="card-header"><h2 className="card-title">Operations map</h2><span className="meta">Select a flight below to display its track</span></div><LiveMap flights={flights} track={track}/></section>
 <section className="card live-table-card"><div className="table-wrap"><table><thead><tr><th>Flight</th><th>Route</th><th>Pilot / aircraft</th><th>Phase</th><th>Altitude / GS</th><th>Fuel</th><th>Connection</th><th>Heartbeat</th></tr></thead><tbody>{flights.map(x=><tr key={x.id} className={selected===x.id?"live-selected":""} onClick={()=>setSelected(x.id)}><td><strong>{x.flightNumber}</strong><span className="secondary">{x.callsign}</span></td><td>{x.departureIcao} → {x.arrivalIcao}</td><td>{x.pilot}<span className="secondary">{x.aircraftRegistration} · {x.aircraftType}</span></td><td>{x.phase}</td><td>{x.altitudeFeet?.toFixed(0)??"—"} ft / {x.groundSpeedKnots?.toFixed(0)??"—"} kt</td><td>{x.fuelKg?.toFixed(0)??"—"} kg</td><td><span className={`badge ${x.connectionStatus==="OFFLINE"?"red":x.connectionStatus==="DELAYED"?"amber":x.connectionStatus==="COMPLETED"?"gray":""}`}>{x.connectionStatus}</span></td><td>{new Date(x.lastHeartbeatAt).toLocaleTimeString()}</td></tr>)}</tbody></table></div>{!flights.length&&<div className="empty-state">No ACARS sessions in the last 24 hours.</div>}</section></>;
}
