import Link from "next/link";
import { Badge, DataTable } from "@/components/data-table";
import { PilotHubNav } from "@/components/pilot-hub-nav";
import { PilotPortalShell } from "@/components/pilot-portal-shell";
import { formatCurrency, formatDate, formatNumber } from "@/lib/i18n/core";
import { getTranslations } from "@/lib/i18n/server";
import { getPilotHubData } from "@/lib/pilot/portalData";
import { requirePilotSession } from "@/lib/pilot/session";
import { CareerProgressBar } from "@/components/career-progress-bar";
export const dynamic="force-dynamic";
export default async function PilotDashboardPage(){const session=await requirePilotSession();const [{locale},hub]=await Promise.all([getTranslations(),getPilotHubData(session.id)]);const number=(value:number,digits=0)=>formatNumber(value,locale,{maximumFractionDigits:digits});return <PilotPortalShell><PilotHubNav/>
  <section className="pilot-identity-card"><div><p className="eyebrow">PILOT PROFILE</p><h1>{hub.pilot.displayName}</h1><p>{hub.pilot.callsign??"Callsign pending"} · {hub.pilot.hubId??hub.pilot.base??"No base"} · Joined {formatDate(hub.pilot.createdAt,locale)}</p></div><div className="pilot-rank-lockup"><span>{hub.rank}</span><small>{hub.pilot.appointment??"Flight Crew"}</small><Badge tone={hub.pilot.status==="active"?"green":"amber"}>{hub.pilot.status}</Badge></div><div className="wallet-lockup"><small>VIRTUAL WALLET</small><strong>{formatCurrency(hub.pilot.walletBalanceCents,locale)}</strong><Link href="/pilot/wallet">View activity →</Link></div></section>
  <section className="grid stats pilot-hub-stats"><div className="card"><div className="stat-label">HISPAFLY Hours</div><div className="stat-value">{number(hub.stats.hispaflyHours,1)}</div></div><div className="card"><div className="stat-label">Sectors</div><div className="stat-value">{hub.stats.acceptedSectors}</div></div><div className="card"><div className="stat-label">Accepted PIREPs</div><div className="stat-value">{number(hub.stats.acceptanceRate,1)}%</div></div><div className="card"><div className="stat-label">Next Rank</div><div className="stat-value">{hub.career.next??"Complete"}</div><div className="stat-note">{hub.career.percent}% complete</div></div></section>
  <div className="pilot-hub-columns"><section className="card"><div className="card-header"><div><h2 className="card-title">Career Progress</h2><p className="meta">Accepted flights update this automatically.</p></div><Link href="/pilot/career">Details</Link></div><CareerProgressBar percent={hub.career.percent}/><p><strong>{hub.career.percent}%</strong> toward {hub.career.next??"the highest rank"}{hub.career.approval?" · staff assessment required":""}</p></section><section className="card"><div className="card-header"><div><h2 className="card-title">Fleet Experience</h2><p className="meta">Logbook statistics only — never an aircraft restriction.</p></div></div>{hub.fleetExperience.length?hub.fleetExperience.slice(0,4).map(row=><div className="fleet-summary-row" key={row.fleet}><strong>{row.fleet}</strong><span>{number(row.hours,1)} h · {row.sectors} sectors</span></div>):<div className="empty-state">No accepted fleet activity yet.</div>}</section></div>
  <section className="card"><div className="card-header"><div><h2 className="card-title">Recent Wallet Activity</h2><p className="meta">Virtual HISPAFLY credits; not real currency.</p></div><Link href="/pilot/wallet">All transactions</Link></div>{hub.recentTransactions.length?<DataTable headers={["Description","Type","Amount","Date"]} rows={hub.recentTransactions.map(row=>[row.description,row.type,<strong key="amount">{row.amountCents>=0?"+":""}{formatCurrency(row.amountCents,locale)}</strong>,formatDate(row.createdAt,locale)])}/>:<div className="empty-state">No wallet activity yet.</div>}</section>
  </PilotPortalShell>}
