import Link from "next/link";
import { Badge, DataTable } from "@/components/data-table";
import { PilotHubNav } from "@/components/pilot-hub-nav";
import { PilotPortalShell } from "@/components/pilot-portal-shell";
import { formatCurrency, formatDate, formatNumber } from "@/lib/i18n/core";
import { getTranslations } from "@/lib/i18n/server";
import { getPilotHubData } from "@/lib/pilot/portalData";
import { requirePilotSession } from "@/lib/pilot/session";
import { CareerProgressBar } from "@/components/career-progress-bar";
export const dynamic="force-dynamic";
export default async function PilotDashboardPage(){const session=await requirePilotSession();const [{locale,t},hub]=await Promise.all([getTranslations(),getPilotHubData(session.id)]);const number=(value:number,digits=0)=>formatNumber(value,locale,{maximumFractionDigits:digits});return <PilotPortalShell><PilotHubNav/>
  <section className="pilot-identity-card"><div><p className="eyebrow">{t("pilotHub.profile")}</p><h1>{hub.pilot.displayName}</h1><p>{hub.pilot.callsign??t("pilotHub.callsignPending")} · {hub.pilot.hubId??hub.pilot.base??t("pilotNav.noBase")} · {t("pilotHub.joined")} {formatDate(hub.pilot.createdAt,locale)}</p></div><div className="pilot-rank-lockup"><span>{hub.rank}</span><small>{hub.pilot.appointment??t("pilotHub.flightCrew")}</small><Badge tone={hub.pilot.status==="active"?"green":"amber"}>{t(`status.${hub.pilot.status}`)}</Badge></div><div className="wallet-lockup"><small>{t("pilotHub.virtualWallet")}</small><strong>{formatCurrency(hub.pilot.walletBalanceCents,locale)}</strong><Link href="/pilot/wallet">{t("pilotHub.viewActivity")}</Link></div></section>
  <section className="grid stats pilot-hub-stats"><div className="card"><div className="stat-label">{t("pilotHub.hours")}</div><div className="stat-value">{number(hub.stats.hispaflyHours,1)}</div></div><div className="card"><div className="stat-label">{t("pilotHub.sectors")}</div><div className="stat-value">{hub.stats.acceptedSectors}</div></div><div className="card"><div className="stat-label">{t("pilotHub.acceptedPireps")}</div><div className="stat-value">{number(hub.stats.acceptanceRate,1)}%</div></div><div className="card"><div className="stat-label">{t("pilotHub.nextRank")}</div><div className="stat-value">{hub.career.next??t("pilotHub.complete")}</div><div className="stat-note">{t("pilotHub.percentComplete",{percent:hub.career.percent})}</div></div></section>
  <div className="pilot-hub-columns"><section className="card"><div className="card-header"><div><h2 className="card-title">{t("pilotHub.careerProgress")}</h2><p className="meta">{t("pilotHub.careerAuto")}</p></div><Link href="/pilot/career">{t("pilotHub.details")}</Link></div><CareerProgressBar percent={hub.career.percent}/><p><strong>{hub.career.percent}%</strong> {t("pilotHub.toward",{rank:hub.career.next??t("pilotHub.highestRank")})}{hub.career.approval?` · ${t("pilotHub.assessment")}`:""}</p></section><section className="card"><div className="card-header"><div><h2 className="card-title">{t("pilotHub.fleetExperience")}</h2><p className="meta">{t("pilotHub.fleetNote")}</p></div></div>{hub.fleetExperience.length?hub.fleetExperience.slice(0,4).map(row=><div className="fleet-summary-row" key={row.fleet}><strong>{row.fleet}</strong><span>{number(row.hours,1)} h · {row.sectors} {t("pilotHub.sectors").toLowerCase()}</span></div>):<div className="empty-state">{t("pilotHub.noFleet")}</div>}</section></div>
  <section className="card"><div className="card-header"><div><h2 className="card-title">{t("pilotHub.recentWallet")}</h2><p className="meta">{t("pilotHub.virtualCredits")}</p></div><Link href="/pilot/wallet">{t("pilotHub.allTransactions")}</Link></div>{hub.recentTransactions.length?<DataTable headers={[t("common.description"),t("common.type"),t("common.amount"),t("common.date")]} rows={hub.recentTransactions.map(row=>[row.description,row.type,<strong key="amount">{row.amountCents>=0?"+":""}{formatCurrency(row.amountCents,locale)}</strong>,formatDate(row.createdAt,locale)])}/>:<div className="empty-state">{t("pilotHub.noWallet")}</div>}</section>
  </PilotPortalShell>}
