"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireStaffPermission } from "@/lib/staff/authorization";
import { archiveFlightScheduleDraft, createFlightScheduleDraft, duplicateFlightScheduleAsDraft, updateFlightScheduleDraft } from "@/lib/native-scheduling/management";
import { generateFlightsForSchedule, publishFlightSchedule, SchedulePublicationError } from "@/lib/native-scheduling/publication";
import { getFlightSchedule } from "@/lib/native-scheduling/repository";

const value = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
const raw = (form: FormData) => ({ code: value(form, "code"), name: value(form, "name"), routeId: value(form, "routeId"), daysOfWeek: form.getAll("daysOfWeek").map(Number), departureTimeMinutesUtc: Number(value(form, "departureTimeMinutesUtc")), scheduledDurationMinutes: Number(value(form, "scheduledDurationMinutes")), defaultFleetId: value(form, "defaultFleetId"), assignedAircraftId: value(form, "assignedAircraftId"), effectiveFrom: value(form, "effectiveFrom"), effectiveUntil: value(form, "effectiveUntil"), bookingOpenOffsetMinutes: Number(value(form, "bookingOpenOffsetMinutes")), bookingCloseOffsetMinutes: Number(value(form, "bookingCloseOffsetMinutes")), generationHorizonDays: Number(value(form, "generationHorizonDays")), notes: value(form, "notes") });
const message = (error: unknown) => encodeURIComponent(error instanceof SchedulePublicationError ? error.message : error instanceof Error ? error.message : "No se pudo completar la operación.");

export async function createProgramacionAction(form: FormData) { let target = "/staff/operations/programacion/new"; try { const staff = await requireStaffPermission("SCHEDULE_CREATE", { entityType: "FlightSchedule", attemptedAction: "create Programación draft" }); const { schedule, validation } = await createFlightScheduleDraft(raw(form), staff); target = `/staff/operations/programacion/${schedule.id}?saved=1&errors=${validation.errors.length}&warnings=${validation.warnings.length}`; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function updateProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}/edit`; try { const staff = await requireStaffPermission("SCHEDULE_EDIT", { entityType: "FlightSchedule", entityId: id, attemptedAction: "edit Programación draft" }); const { validation } = await updateFlightScheduleDraft(id, raw(form), staff); target = `/staff/operations/programacion/${id}?saved=1&errors=${validation.errors.length}&warnings=${validation.warnings.length}`; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function duplicateProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}`; try { const staff = await requireStaffPermission("SCHEDULE_CREATE", { entityType: "FlightSchedule", entityId: id, attemptedAction: "duplicate Programación draft" }); const { schedule } = await duplicateFlightScheduleAsDraft(id, { code: value(form, "code"), effectiveFrom: value(form, "effectiveFrom"), effectiveUntil: value(form, "effectiveUntil") }, staff); target = `/staff/operations/programacion/${schedule.id}?duplicated=1`; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function archiveProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}`; try { const staff = await requireStaffPermission("SCHEDULE_STATUS_MANAGE", { entityType: "FlightSchedule", entityId: id, attemptedAction: "archive Programación draft" }); await archiveFlightScheduleDraft(id, staff); target = "/staff/operations/programacion?archived=1"; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function publishProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}`; try { const staff = await requireStaffPermission("SCHEDULE_STATUS_MANAGE", { entityType: "FlightSchedule", entityId: id, attemptedAction: "publish Programación" }); const result = await publishFlightSchedule({ scheduleId: id, warningFingerprint: value(form, "acknowledged") === "yes" ? value(form, "warningFingerprint") : undefined, actor: staff }); target += `?published=1&created=${result.generation.created}&existing=${result.generation.existing}`; revalidatePath("/staff/operations/programacion"); revalidatePath(`/staff/operations/programacion/${id}`); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function generateProgramacionFlightsAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}`; try { const staff = await requireStaffPermission("SCHEDULE_STATUS_MANAGE", { entityType: "FlightSchedule", entityId: id, attemptedAction: "extend Programación horizon" }); const result = await generateFlightsForSchedule({ scheduleId: id, actor: staff }); target += `?generated=1&created=${result.created}&existing=${result.existing}`; revalidatePath(`/staff/operations/programacion/${id}`); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function applyPlannerDaysAction(form: FormData) { const id=value(form,"id"), aircraftId=value(form,"aircraftId"), week=value(form,"week"); let target=`/staff/operations/programacion/planner?aircraftId=${encodeURIComponent(aircraftId)}&week=${encodeURIComponent(week)}`; try { const staff=await requireStaffPermission("SCHEDULE_EDIT",{entityType:"FlightSchedule",entityId:id,attemptedAction:"apply planner operating days"}); const schedule=await getFlightSchedule(id); if(!schedule) throw new Error("La programación no existe."); await updateFlightScheduleDraft(id,{code:schedule.code,name:schedule.name,routeId:schedule.routeId,daysOfWeek:form.getAll("daysOfWeek").map(Number),departureTimeMinutesUtc:schedule.departureTimeMinutesUtc,scheduledDurationMinutes:schedule.scheduledDurationMinutes,defaultFleetId:schedule.defaultFleetId,assignedAircraftId:schedule.assignedAircraftId,effectiveFrom:schedule.effectiveFrom.toISOString().slice(0,10),effectiveUntil:schedule.effectiveUntil?.toISOString().slice(0,10)??"",bookingOpenOffsetMinutes:schedule.bookingOpenOffsetMinutes,bookingCloseOffsetMinutes:schedule.bookingCloseOffsetMinutes,generationHorizonDays:schedule.generationHorizonDays,notes:schedule.notes},staff); revalidatePath("/staff/operations/programacion/planner"); target+=`&selected=${id}&daysApplied=1`; } catch(error){ target+=`&error=${message(error)}`; } redirect(target); }
