"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireStaffPermission } from "@/lib/staff/authorization";
import { archiveFlightScheduleDraft, createFlightScheduleDraft, duplicateFlightScheduleAsDraft, updateFlightScheduleDraft } from "@/lib/native-scheduling/management";

const value = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
const raw = (form: FormData) => ({ code: value(form, "code"), name: value(form, "name"), routeId: value(form, "routeId"), daysOfWeek: form.getAll("daysOfWeek").map(Number), departureTimeMinutesUtc: Number(value(form, "departureTimeMinutesUtc")), scheduledDurationMinutes: Number(value(form, "scheduledDurationMinutes")), defaultFleetId: value(form, "defaultFleetId"), assignedAircraftId: value(form, "assignedAircraftId"), effectiveFrom: value(form, "effectiveFrom"), effectiveUntil: value(form, "effectiveUntil"), bookingOpenOffsetMinutes: Number(value(form, "bookingOpenOffsetMinutes")), bookingCloseOffsetMinutes: Number(value(form, "bookingCloseOffsetMinutes")), generationHorizonDays: Number(value(form, "generationHorizonDays")), notes: value(form, "notes") });
const message = (error: unknown) => encodeURIComponent(error instanceof Error ? error.message : "No se pudo completar la operación.");

export async function createProgramacionAction(form: FormData) { let target = "/staff/operations/programacion/new"; try { const staff = await requireStaffPermission("SCHEDULE_CREATE", { entityType: "FlightSchedule", attemptedAction: "create Programación draft" }); const { schedule, validation } = await createFlightScheduleDraft(raw(form), staff); target = `/staff/operations/programacion/${schedule.id}?saved=1&errors=${validation.errors.length}&warnings=${validation.warnings.length}`; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function updateProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}/edit`; try { const staff = await requireStaffPermission("SCHEDULE_EDIT", { entityType: "FlightSchedule", entityId: id, attemptedAction: "edit Programación draft" }); const { validation } = await updateFlightScheduleDraft(id, raw(form), staff); target = `/staff/operations/programacion/${id}?saved=1&errors=${validation.errors.length}&warnings=${validation.warnings.length}`; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function duplicateProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}`; try { const staff = await requireStaffPermission("SCHEDULE_CREATE", { entityType: "FlightSchedule", entityId: id, attemptedAction: "duplicate Programación draft" }); const { schedule } = await duplicateFlightScheduleAsDraft(id, { code: value(form, "code"), effectiveFrom: value(form, "effectiveFrom"), effectiveUntil: value(form, "effectiveUntil") }, staff); target = `/staff/operations/programacion/${schedule.id}?duplicated=1`; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
export async function archiveProgramacionAction(form: FormData) { const id = value(form, "id"); let target = `/staff/operations/programacion/${id}`; try { const staff = await requireStaffPermission("SCHEDULE_STATUS_MANAGE", { entityType: "FlightSchedule", entityId: id, attemptedAction: "archive Programación draft" }); await archiveFlightScheduleDraft(id, staff); target = "/staff/operations/programacion?archived=1"; revalidatePath("/staff/operations/programacion"); } catch (error) { target += `?error=${message(error)}`; } redirect(target); }
