import Link from "next/link";
import { listFlightSchedules, listScheduleFormOptions } from "@/lib/native-scheduling/repository";
import { validateProposedSchedule } from "@/lib/native-scheduling/service";
import { formatDate, formatDays, formatDuration, formatMinutes, toProposedSchedule } from "@/lib/native-scheduling/presentation";
import { getCurrentStaff } from "@/lib/staff/currentStaff";
import { staffHasPermission } from "@/lib/staff/permissions";

const qs = (query: Record<string, string | undefined>, page: number) => `?${new URLSearchParams({ ...Object.fromEntries(Object.entries(query).filter(([, value]) => value)), page: String(page) }).toString()}`;
export default async function ProgramacionPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const query = await searchParams;
  const [result, options, staff] = await Promise.all([listFlightSchedules({ search: query.search, status: query.status, fleetId: query.fleetId, aircraftId: query.aircraftId, effectiveDate: query.effectiveDate, page: Number(query.page) || 1 }), listScheduleFormOptions(), getCurrentStaff()]);
  const validated = await Promise.all(result.rows.map(async (schedule) => ({ schedule, validation: await validateProposedSchedule(toProposedSchedule(schedule), { excludeScheduleId: schedule.id }) })));
  const rows = query.validation ? validated.filter(({ validation }) => query.validation === "valid" ? validation.valid && !validation.warnings.length : query.validation === "warnings" ? validation.valid && validation.warnings.length : !validation.valid) : validated;
  return <><div className="page-header"><div><div className="eyebrow">OPERACIONES</div><h1>Programación</h1><p>Gestión de borradores de la programación semanal de HISPAFLY.</p></div>{staffHasPermission(staff, "SCHEDULE_CREATE") && <Link className="button" href="/staff/operations/programacion/new">Nueva programación</Link>}</div>
    {query.archived && <div className="notice">Borrador archivado correctamente.</div>}
    <form className="audit-filters"><label>Buscar<input name="search" defaultValue={query.search} placeholder="Código, vuelo, ruta o aeropuerto"/></label><label>Estado<select name="status" defaultValue={query.status ?? ""}><option value="">Todos</option>{["DRAFT","ACTIVE","SUSPENDED","EXPIRED","ARCHIVED"].map((status) => <option key={status}>{status}</option>)}</select></label><label>Flota<select name="fleetId" defaultValue={query.fleetId ?? ""}><option value="">Todas</option>{options[1].map((fleet) => <option key={fleet.id} value={fleet.id}>{fleet.code ?? fleet.name}</option>)}</select></label><label>Aeronave<select name="aircraftId" defaultValue={query.aircraftId ?? ""}><option value="">Todas</option>{options[2].map((item) => <option key={item.id} value={item.id}>{item.registration}</option>)}</select></label><label>Vigente el<input type="date" name="effectiveDate" defaultValue={query.effectiveDate}/></label><label>Validación<select name="validation" defaultValue={query.validation ?? ""}><option value="">Todas</option><option value="valid">Válidas</option><option value="conflicts">Con conflictos</option><option value="warnings">Con advertencias</option></select></label><button className="button secondary">Filtrar</button></form>
    <div className="table-wrap programacion-table"><table><thead><tr><th>Programación</th><th>Ruta</th><th>Días</th><th>Horario UTC</th><th>Duración</th><th>Flota / Aeronave</th><th>Vigencia</th><th>Estado</th><th>Validación</th><th>Acciones</th></tr></thead><tbody>{rows.map(({ schedule, validation }) => <tr key={schedule.id}><td><strong>{schedule.code}</strong><br/><span>{schedule.route.flightNumber ?? "—"}</span></td><td>{schedule.route.departure} → {schedule.route.arrival}</td><td>{formatDays(schedule.daysOfWeek)}</td><td>{formatMinutes(schedule.departureTimeMinutesUtc)} → {formatMinutes(schedule.arrivalTimeMinutesUtc)}</td><td>{formatDuration(schedule.scheduledDurationMinutes)}</td><td>{schedule.defaultFleet?.code ?? "Libre"}<br/>{schedule.assignedAircraft?.registration ?? "Sin asignar"}</td><td>{formatDate(schedule.effectiveFrom)} → {formatDate(schedule.effectiveUntil)}</td><td><span className={`badge schedule-${schedule.status.toLowerCase()}`}>{schedule.status}</span></td><td><span className={`badge ${validation.valid ? validation.warnings.length ? "amber" : "" : "red"}`}>{validation.valid ? validation.warnings.length ? "ADVERTENCIAS" : "VÁLIDA" : `${validation.errors.length} CONFLICTOS`}</span></td><td><Link href={`/staff/operations/programacion/${schedule.id}`}>Ver</Link>{schedule.status === "DRAFT" && staffHasPermission(staff, "SCHEDULE_EDIT") && <> · <Link href={`/staff/operations/programacion/${schedule.id}/edit`}>Editar</Link></>}</td></tr>)}</tbody></table></div>
    {!rows.length && <div className="empty-state">No hay programaciones que coincidan con los filtros.</div>}<div className="button-row"><span>{result.total} programaciones</span>{result.page > 1 && <Link href={qs(query, result.page - 1)}>Anterior</Link>}{result.page * result.pageSize < result.total && <Link href={qs(query, result.page + 1)}>Siguiente</Link>}</div>
  </>;
}
