"use server";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { hashPassword } from "@/lib/auth/password";
import { requireStaffPermission } from "@/lib/staff/authorization";
const value=(form:FormData,key:string)=>String(form.get(key)??"").trim();
export async function createPilotIdentity(form:FormData){
  const pilotId=value(form,"pilotId"),email=value(form,"email").toLowerCase(),username=value(form,"username").toLowerCase(),password=value(form,"temporaryPassword");
  const staff=await requireStaffPermission("STAFF_EDIT",{entityType:"Pilot",entityId:pilotId,attemptedAction:"create local Pilot identity"});
  const pilot=await prisma.pilot.findUnique({where:{id:pilotId}});if(!pilot||pilot.authUserId)redirect("/staff/pilots?error=identity_unavailable");
  try{const passwordHash=await hashPassword(password);await prisma.$transaction(async tx=>{const role=await tx.authRole.findUnique({where:{code:"PILOT"}});if(!role)throw new Error("PILOT role is not installed.");const user=await tx.authUser.create({data:{email,username,displayName:pilot.displayName,passwordHash,status:"ACTIVE",emailVerifiedAt:new Date(),roles:{create:{roleId:role.id}}}});await tx.pilot.update({where:{id:pilot.id},data:{authUserId:user.id,email:pilot.email??email,username:pilot.username??username}});await tx.aocAuditLog.create({data:{staffUserId:staff.id,action:"PILOT_IDENTITY_CREATED",entityType:"AuthUser",entityId:user.id,message:`Created local identity for ${pilot.displayName}.`,metadata:{pilotId:pilot.id}}});});}catch(error){redirect(`/staff/pilots?error=${encodeURIComponent(error instanceof Error?error.message:"identity_creation_failed")}`);}redirect("/staff/pilots?success=identity_created");
}
export async function setPilotIdentityStatus(form:FormData){const userId=value(form,"userId"),enabled=value(form,"enabled")==="true";const staff=await requireStaffPermission("STAFF_EDIT",{entityType:"AuthUser",entityId:userId,attemptedAction:enabled?"enable Pilot identity":"disable Pilot identity"});await prisma.$transaction([prisma.authUser.update({where:{id:userId},data:{status:enabled?"ACTIVE":"DISABLED",lockedUntil:null,failedLoginAttempts:0}}),...(!enabled?[prisma.authSession.updateMany({where:{userId,revokedAt:null},data:{revokedAt:new Date()}})]:[]),prisma.aocAuditLog.create({data:{staffUserId:staff.id,action:enabled?"PILOT_IDENTITY_ENABLED":"PILOT_IDENTITY_DISABLED",entityType:"AuthUser",entityId:userId,message:`Pilot identity ${enabled?"enabled":"disabled"}.`}})]);redirect("/staff/pilots?success=identity_updated");}
export async function setPilotTemporaryPassword(form:FormData){const userId=value(form,"userId"),password=value(form,"temporaryPassword");const staff=await requireStaffPermission("STAFF_EDIT",{entityType:"AuthUser",entityId:userId,attemptedAction:"reset Pilot password"});const passwordHash=await hashPassword(password);await prisma.$transaction([prisma.authUser.update({where:{id:userId},data:{passwordHash,passwordChangedAt:new Date(),status:"ACTIVE",lockedUntil:null,failedLoginAttempts:0}}),prisma.authSession.updateMany({where:{userId,revokedAt:null},data:{revokedAt:new Date()}}),prisma.aocAuditLog.create({data:{staffUserId:staff.id,action:"PILOT_PASSWORD_RESET_BY_ADMIN",entityType:"AuthUser",entityId:userId,message:"Pilot password reset by Staff."}})]);redirect("/staff/pilots?success=password_reset");}
