ALTER TYPE "RouteOperationalStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE "AirportStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';

ALTER TABLE "Airport" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "networkPolicy" TEXT;
ALTER TABLE "Route" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
