export const PERMISSION_GROUPS = {
  GENERAL: ["DASHBOARD_VIEW"],
  STAFF: ["STAFF_VIEW", "STAFF_CREATE", "STAFF_EDIT", "STAFF_DISABLE", "STAFF_PERMISSION_MANAGE", "STAFF_CREDENTIAL_MANAGE", "ROLE_VIEW", "ROLE_MANAGE"],
  PILOTS: ["PILOT_VIEW", "PILOT_CREATE", "PILOT_EDIT", "PILOT_NOTE_MANAGE", "PILOT_STATUS_MANAGE", "PILOT_IDENTITY_MANAGE", "PILOT_PASSWORD_RESET", "PILOT_MERGE", "PILOT_DELETE"],
  FLEET: ["FLEET_VIEW", "FLEET_SYNC", "FLEET_CREATE", "FLEET_EDIT", "FLEET_DISABLE"],
  AIRCRAFT: ["AIRCRAFT_VIEW", "AIRCRAFT_SYNC", "AIRCRAFT_CREATE", "AIRCRAFT_EDIT", "AIRCRAFT_DISABLE", "PUBLIC_FLEET_MANAGE"],
  LOCATION: ["FLEET_LOCATION_VIEW", "FLEET_LOCATION_SYNC", "FLEET_LOCATION_EDIT"],
  ENGINEERING: ["AIRCRAFT_PERFORMANCE_VIEW", "AIRCRAFT_PERFORMANCE_EDIT", "AIRCRAFT_CONDITION_VIEW", "AIRCRAFT_CONDITION_EDIT", "AIRCRAFT_MAINTENANCE_MANAGE", "AIRCRAFT_AOG_DECLARE"],
  ROUTES: ["ROUTE_VIEW", "ROUTE_SYNC", "ROUTE_CREATE", "ROUTE_EDIT", "ROUTE_ARCHIVE"],
  OPERATIONS: ["FLIGHT_OFFER_VIEW", "FLIGHT_OFFER_CREATE", "FLIGHT_OFFER_EDIT", "FLIGHT_OFFER_CANCEL", "OFP_VIEW", "OFP_MANAGE", "OFP_RELEASE", "FUEL_POLICY_VIEW", "FUEL_POLICY_MANAGE"],
  PIREPS: ["PIREP_VIEW", "PIREP_SYNC", "PIREP_SCORE", "PIREP_ACCEPT", "PIREP_REJECT"],
  PAYROLL: ["PAYROLL_VIEW", "PAYROLL_RECALCULATE", "PAYROLL_APPROVE", "PAYROLL_REJECT", "PAYROLL_MARK_PAID"],
  FINANCE: ["ECONOMY_VIEW", "EXPENSE_VIEW", "EXPENSE_RULE_VIEW", "EXPENSE_RULE_MANAGE", "WALLET_VIEW", "WALLET_ADJUST"],
  SYSTEM: ["AUDIT_LOG_VIEW", "VAMSYS_CONNECTION_VIEW", "VAMSYS_CONNECTION_MANAGE", "OPERATIONS_API_VIEW", "OPERATIONS_API_MANAGE", "SYSTEM_SETTINGS_VIEW", "SYSTEM_SETTINGS_MANAGE"],
} as const;

export const PERMISSION_CODES = Object.values(PERMISSION_GROUPS).flat();
export type StaffPermissionCode = typeof PERMISSION_CODES[number];

export const DANGEROUS_PERMISSIONS = new Set<StaffPermissionCode>([
  "STAFF_PERMISSION_MANAGE",
  "STAFF_CREDENTIAL_MANAGE",
  "ROLE_MANAGE",
  "PILOT_PASSWORD_RESET",
  "PILOT_MERGE",
  "PILOT_DELETE",
  "AIRCRAFT_AOG_DECLARE",
  "ROUTE_ARCHIVE",
  "PIREP_ACCEPT",
  "PIREP_REJECT",
  "PAYROLL_APPROVE",
  "PAYROLL_REJECT",
  "PAYROLL_MARK_PAID",
  "WALLET_ADJUST",
  "VAMSYS_CONNECTION_MANAGE",
  "OPERATIONS_API_MANAGE",
  "SYSTEM_SETTINGS_MANAGE",
]);

const all = [...PERMISSION_CODES];
const viewerExcluded = new Set(["VAMSYS_CONNECTION_VIEW", "OPERATIONS_API_VIEW", "SYSTEM_SETTINGS_VIEW"]);
const readOnly = all.filter((code) => (code.endsWith("_VIEW") || code === "AUDIT_LOG_VIEW") && !viewerExcluded.has(code));

export const ROLE_TEMPLATE_PERMISSIONS = {
  OWNER: all,
  ADMIN: all,
  NETWORK_PLANNING: ["DASHBOARD_VIEW", "ROUTE_VIEW", "ROUTE_SYNC", "ROUTE_CREATE", "ROUTE_EDIT", "ROUTE_ARCHIVE", "FLEET_VIEW", "AIRCRAFT_VIEW", "AIRCRAFT_PERFORMANCE_VIEW", "FLIGHT_OFFER_VIEW", "FLIGHT_OFFER_CREATE", "FLIGHT_OFFER_EDIT", "PIREP_VIEW", "FUEL_POLICY_VIEW", "ECONOMY_VIEW", "EXPENSE_VIEW", "AUDIT_LOG_VIEW"],
  FLEET_MANAGER: ["DASHBOARD_VIEW", "FLEET_VIEW", "FLEET_SYNC", "FLEET_CREATE", "FLEET_EDIT", "FLEET_DISABLE", "AIRCRAFT_VIEW", "AIRCRAFT_SYNC", "AIRCRAFT_CREATE", "AIRCRAFT_EDIT", "AIRCRAFT_DISABLE", "PUBLIC_FLEET_MANAGE", "FLEET_LOCATION_VIEW", "FLEET_LOCATION_SYNC", "FLEET_LOCATION_EDIT", "AIRCRAFT_PERFORMANCE_VIEW", "AIRCRAFT_PERFORMANCE_EDIT", "AIRCRAFT_CONDITION_VIEW", "AIRCRAFT_CONDITION_EDIT", "AIRCRAFT_MAINTENANCE_MANAGE", "AIRCRAFT_AOG_DECLARE", "ROUTE_VIEW", "FLIGHT_OFFER_VIEW", "PIREP_VIEW", "OFP_VIEW", "FUEL_POLICY_VIEW", "ECONOMY_VIEW", "EXPENSE_VIEW", "AUDIT_LOG_VIEW"],
  HR_MANAGER: ["DASHBOARD_VIEW", "PILOT_VIEW", "PILOT_CREATE", "PILOT_EDIT", "PILOT_NOTE_MANAGE", "PILOT_STATUS_MANAGE", "PILOT_IDENTITY_MANAGE", "PILOT_PASSWORD_RESET", "PILOT_MERGE", "AUDIT_LOG_VIEW"],
  VIEWER: readOnly,
  LEGACY_OPS: ["PAYROLL_APPROVE", "PAYROLL_REJECT", "PAYROLL_RECALCULATE", "PIREP_SYNC", "FLIGHT_OFFER_VIEW", "FLIGHT_OFFER_CREATE", "FLIGHT_OFFER_EDIT", "FLIGHT_OFFER_CANCEL", "ROUTE_VIEW", "ROUTE_SYNC", "ROUTE_CREATE", "ROUTE_EDIT", "ROUTE_ARCHIVE", "FLEET_VIEW", "FLEET_SYNC", "FLEET_CREATE", "FLEET_EDIT", "AIRCRAFT_VIEW", "AIRCRAFT_SYNC", "AIRCRAFT_CREATE", "AIRCRAFT_EDIT"],
  LEGACY_FINANCE: ["PAYROLL_VIEW", "PAYROLL_MARK_PAID"],
} satisfies Record<string, readonly StaffPermissionCode[]>;

export function isKnownPermission(value: string): value is StaffPermissionCode {
  return (PERMISSION_CODES as readonly string[]).includes(value);
}
