"use server";
import type { FleetOperationalStatus } from "@prisma/client";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { changeFleetStatus, copyFleetToNativeDraft, createNativeFleet, updateNativeFleet } from "@/lib/native-flight/fleet";
import { requireStaffPermission } from "@/lib/staff/authorization";
const v=(f:FormData,k:string)=>String(f.get(k)??"").trim(), n=(f:FormData,k:string)=>v(f,k)===""?null:Number(v(f,k));
const input=(f:FormData)=>({code:v(f,"code"),name:v(f,"name"),type:v(f,"type"),iataType:v(f,"iataType"),manufacturer:v(f,"manufacturer"),family:v(f,"family"),variant:v(f,"variant"),engineType:v(f,"engineType"),typicalSeatCapacity:n(f,"typicalSeatCapacity"),maxPassengers:n(f,"maxPassengers"),maxCargoKg:n(f,"maxCargoKg"),rangeNm:n(f,"rangeNm"),cruiseSpeedKts:n(f,"cruiseSpeedKts"),defaultCruiseAltitudeFt:n(f,"defaultCruiseAltitudeFt"),etopsMinutes:n(f,"etopsMinutes"),internalNotes:v(f,"internalNotes")});
export async function createFleetAction(f:FormData){let t="/staff/fleets/new";try{const s=await requireStaffPermission("FLEET_CREATE",{entityType:"Fleet",attemptedAction:"create Native fleet"}),x=await createNativeFleet(input(f),s);t=`/staff/fleets/${x.id}?success=Fleet%20created.`}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Creation failed.")}`}redirect(t)}
export async function updateFleetAction(f:FormData){const id=v(f,"id");let t=`/staff/fleets/${id}/edit`;try{const s=await requireStaffPermission("FLEET_EDIT",{entityType:"Fleet",entityId:id,attemptedAction:"edit Native fleet"});await updateNativeFleet(id,input(f),s);t=`/staff/fleets/${id}?success=Fleet%20updated.`}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Update failed.")}`}redirect(t)}
export async function changeFleetStatusAction(f:FormData){const id=v(f,"id"),status=v(f,"status") as FleetOperationalStatus;let t=`/staff/fleets/${id}`;try{const p=status==="ARCHIVED"?"FLEET_ARCHIVE":"FLEET_EDIT",s=await requireStaffPermission(p,{entityType:"Fleet",entityId:id,attemptedAction:`change Fleet to ${status}`});await changeFleetStatus(id,status,s,v(f,"reason"));t+="?success=Fleet%20status%20updated."}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Status change failed.")}`}redirect(t)}
export async function copyFleetAction(f:FormData){const id=v(f,"id");let t=`/staff/fleets/${id}`;try{const s=await requireStaffPermission("FLEET_CREATE",{entityType:"Fleet",entityId:id,attemptedAction:"copy Legacy Fleet"}),x=await copyFleetToNativeDraft(id,v(f,"code"),s);t=`/staff/fleets/${x.id}?success=Native%20draft%20created.`}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Copy failed.")}`}redirect(t)}
export async function compatibilityAction(f:FormData){const fleetId=v(f,"id"),routeId=v(f,"routeId"),policy=v(f,"policy") as "ALLOWED"|"FORBIDDEN";let t=`/staff/fleets/${fleetId}`;try{const s=await requireStaffPermission("FLEET_EDIT",{entityType:"Fleet",entityId:fleetId,attemptedAction:"manage Route Fleet compatibility"}),fleet=await prisma.fleet.findUnique({where:{id:fleetId}}),route=await prisma.route.findUnique({where:{id:routeId}});if(!fleet||fleet.operationalStatus!=="ACTIVE"||!route)throw new Error("Compatibility requires an active Fleet and an existing Route.");const row=await prisma.routeFleetCompatibility.upsert({where:{routeId_fleetId:{routeId,fleetId}},create:{routeId,fleetId,policy,notes:v(f,"notes")||null},update:{policy,notes:v(f,"notes")||null}});await prisma.aocAuditLog.create({data:{staffUserId:s.id==="development-staff"?null:s.id,action:"ROUTE_FLEET_COMPATIBILITY_UPDATED",entityType:"RouteFleetCompatibility",entityId:row.id,message:`${s.name} set ${fleet.code} ${policy} for ${route.routeCode}.`,metadata:{routeId,fleetId,policy}}});t+="?success=Compatibility%20updated."}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Compatibility failed.")}`}redirect(t)}
