"use server";import type{NativeAircraftStatus}from"@prisma/client";import{redirect}from"next/navigation";import{changeAircraftStatus,copyAircraftToNative,correctAircraftTotals,createNativeAircraft,setNativeAircraftLocation,updateNativeAircraft}from"@/lib/native-flight/aircraft";import{requireStaffPermission}from"@/lib/staff/authorization";
const v=(f:FormData,k:string)=>String(f.get(k)??"").trim(),n=(f:FormData,k:string)=>v(f,k)===""?null:Number(v(f,k)),d=(f:FormData,k:string)=>v(f,k)?new Date(`${v(f,k)}T00:00:00Z`):null;
const input=(f:FormData)=>({registration:v(f,"registration"),aircraftType:v(f,"aircraftType"),fleetId:v(f,"fleetId"),name:v(f,"name"),serialNumber:v(f,"serialNumber"),selcal:v(f,"selcal"),deliveryDate:d(f,"deliveryDate"),inServiceDate:d(f,"inServiceDate"),cabinConfiguration:v(f,"cabinConfiguration"),seatCapacity:n(f,"seatCapacity"),cargoCapacityKg:n(f,"cargoCapacityKg"),internalNotes:v(f,"internalNotes")});
export async function createAircraftAction(f:FormData){let t="/staff/aircraft/new";try{const s=await requireStaffPermission("AIRCRAFT_CREATE",{entityType:"Aircraft",attemptedAction:"create Native Aircraft"}),x=await createNativeAircraft(input(f),s);t=`/staff/aircraft/${x.id}?success=Aircraft%20created.`}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Creation failed.")}`}redirect(t)}
export async function updateAircraftAction(f:FormData){const id=v(f,"id");let t=`/staff/aircraft/${id}/edit`;try{const s=await requireStaffPermission("AIRCRAFT_EDIT",{entityType:"Aircraft",entityId:id,attemptedAction:"edit Aircraft"});await updateNativeAircraft(id,input(f),s);t=`/staff/aircraft/${id}?success=Aircraft%20updated.`}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Update failed.")}`}redirect(t)}
export async function statusAction(f:FormData){const id=v(f,"id"),status=v(f,"status") as NativeAircraftStatus;let t=`/staff/aircraft/${id}`;try{const p=status==="RETIRED"?"AIRCRAFT_ARCHIVE":"AIRCRAFT_STATUS_MANAGE",s=await requireStaffPermission(p,{entityType:"Aircraft",entityId:id,attemptedAction:`change Aircraft to ${status}`});await changeAircraftStatus(id,status,s,v(f,"reason"));t+="?success=Status%20updated."}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Status failed.")}`}redirect(t)}
export async function locationAction(f:FormData){const id=v(f,"id");let t=`/staff/aircraft/${id}`;try{const s=await requireStaffPermission("AIRCRAFT_LOCATION_MANAGE",{entityType:"Aircraft",entityId:id,attemptedAction:"manually correct Aircraft location"});await setNativeAircraftLocation(id,v(f,"airportId")||null,{latitude:n(f,"latitude"),longitude:n(f,"longitude")},v(f,"status") as NativeAircraftStatus,v(f,"notes"),v(f,"reason"),s);t+="?success=Location%20updated."}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Location failed.")}`}redirect(t)}
export async function totalsAction(f:FormData){const id=v(f,"id");let t=`/staff/aircraft/${id}`;try{const s=await requireStaffPermission("AIRCRAFT_EDIT",{entityType:"Aircraft",entityId:id,attemptedAction:"correct Aircraft hours and cycles"});await correctAircraftTotals(id,Number(v(f,"totalFlightMinutes")),Number(v(f,"totalCycles")),v(f,"reason"),s);t+="?success=Totals%20corrected."}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Correction failed.")}`}redirect(t)}
export async function copyAircraftAction(f:FormData){const id=v(f,"id");let t=`/staff/aircraft/${id}`;try{const s=await requireStaffPermission("AIRCRAFT_CREATE",{entityType:"Aircraft",entityId:id,attemptedAction:"copy Legacy Aircraft"}),x=await copyAircraftToNative(id,v(f,"registration"),v(f,"fleetId"),s);t=`/staff/aircraft/${x.id}?success=Native%20Aircraft%20created.`}catch(e){t+=`?error=${encodeURIComponent(e instanceof Error?e.message:"Copy failed.")}`}redirect(t)}
