import Link from "next/link";
import { registerAction } from "./actions";
import { prisma } from "@/lib/prisma";
import { HISPAFLY_HUB_ICAOS } from "@/lib/native-flight/hubs";

export const dynamic = "force-dynamic";
const messages: Record<string,string> = { passwords_do_not_match: "The passwords do not match.", account_already_exists: "This email or username is already registered.", verification_email_failed: "Your account exists, but the verification email could not be sent. Please check the email configuration or try again later.", "Invalid registration details.": "Please check your name, email and username.", "Invalid Pilot HUB.": "Select a valid HISPAFLY HUB." };

export default async function RegisterPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [q, hubs] = await Promise.all([searchParams, prisma.airport.findMany({ where: { status: "ACTIVE", archivedAt: null, icao: { in: [...HISPAFLY_HUB_ICAOS] } }, select: { id: true, icao: true, name: true, city: true }, orderBy: { icao: "asc" } })]);
  return <main className="portal-gateway admin-login-gateway"><section className="login-panel"><div className="login-copy"><span>HISPAFLY IDENTITY</span><h1>Join Hispafly</h1><p>Create your Pilot account and select your home HUB. Your initial crew position will be set at that HUB.</p><Link href="/login">Already registered? Sign in</Link><br/><Link href="/resend-verification">Didn&apos;t receive the verification email?</Link></div><form className="login-form" action={registerAction}>{q.error&&<div className="feedback error">{messages[q.error]??"Registration could not be completed. Please try again."}</div>}<label>First name<input name="firstName" required maxLength={80}/></label><label>Last name<input name="lastName" required maxLength={80}/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Username<input name="username" minLength={3} maxLength={30} pattern="[A-Za-z0-9._-]+" autoComplete="username" required/></label><label>Callsign (optional)<input name="callsign" maxLength={20}/></label><label>Home HUB<select name="hubAirportId" required defaultValue=""><option value="" disabled>Select your HUB</option>{hubs.map((hub)=><option key={hub.id} value={hub.id}>{hub.icao} · {hub.city??hub.name??"HISPAFLY HUB"}</option>)}</select><small>Your first crew position will be this airport.</small></label><label>Password<input name="password" type="password" minLength={12} autoComplete="new-password" required/></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} autoComplete="new-password" required/></label><button className="button">CREATE ACCOUNT</button></form></section></main>;
}
